use dsm_gen::generators::kotlin::KotlinGenerator;
use dsm_gen::generators::rust_gen::RustGenerator;
use dsm_gen::generators::swift::SwiftGenerator;
use dsm_gen::generators::typescript::TypeScriptGenerator;
use dsm_gen::generators::CodeGenerator;
use dsm_gen::schema::{
    AssetDefinition, DsmSpecification, FulfillmentConditionSpec, MultiSignatureSpec,
    PolicySpecification, VaultSpecification,
};

// ------------------------------------------------------------------
// Helper: build a minimal VaultSpec with Multi-Signature condition.
// ------------------------------------------------------------------
fn multi_sig_vault_spec() -> VaultSpecification {
    VaultSpecification {
        name: "MultiSigVault".to_string(),
        version: "1.0.0".to_string(),
        description: Some("Integration test vault – multi-sig condition".to_string()),
        fulfillment_condition: FulfillmentConditionSpec::MultiSignature(MultiSignatureSpec {
            public_keys: vec![
                "PUBKEY1AAAAAAAAA".to_string(),
                "PUBKEY2AAAAAAAAA".to_string(),
            ],
            threshold: 2,
        }),
        assets: vec![AssetDefinition {
            asset_id: "DSM".to_string(),
            amount: 5000,
            chain_state_hash: None,
            chain_state_number: None,
            metadata: None,
        }],
        tick_lock: None,
        recovery: None,
        metadata: None,
    }
}

// ------------------------------------------------------------------
// Policy generation tests (existing + extended)
// ------------------------------------------------------------------
#[test]
fn test_enhanced_policy_client_generation() {
    let policy_spec = PolicySpecification::example("TestPolicy".to_string());
    let spec = DsmSpecification::Policy(policy_spec);
    let generator = RustGenerator::new(false, false);

    let generated_code = match generator.generate(&spec) {
        Ok(code) => code,
        Err(err) => panic!("policy generation failed: {err}"),
    };

    assert!(generated_code.contains("PolicyConfig"));
    assert!(generated_code.contains("TransferRule"));
    assert!(generated_code.contains("RuleCondition"));
    assert!(generated_code.contains("ConditionType"));
    assert!(generated_code.contains("RuleAction"));
    assert!(generated_code.contains("PolicyEvaluationResult"));
    assert!(generated_code.contains("TransactionContext"));
    assert!(generated_code.contains("PolicyClient"));
    assert!(generated_code.contains("config: PolicyConfig"));
    assert!(generated_code.contains("evaluate_transaction"));
    assert!(generated_code.contains("evaluate_amount_limit"));
    assert!(generated_code.contains("evaluate_iteration_window"));
    assert!(generated_code.contains("evaluate_whitelist"));
    assert!(generated_code.contains("evaluate_blacklist"));
    assert!(generated_code.contains("evaluate_signature_required"));
    assert!(generated_code.contains("evaluate_custom_condition"));

    // Invariant #2: no serde_json in generated code
    assert!(!generated_code.contains("serde_json"));
    // Invariant #4: no wall-clock
    assert!(!generated_code.contains("duration_seconds"));
    assert!(!generated_code.contains("time_window_hours"));
}

// ------------------------------------------------------------------
// Vault generation tests – all four languages
// ------------------------------------------------------------------

#[test]
fn test_vault_generation_rust() -> Result<(), Box<dyn std::error::Error>> {
    let spec = DsmSpecification::Vault(multi_sig_vault_spec());
    let generator = RustGenerator::new(true, true);
    let code = generator.generate(&spec)?;

    assert!(code.contains("auto-generated by dsm-gen"));
    assert!(code.contains("MultiSigVaultClient"));
    assert!(code.contains("enum FulfillmentCondition"));
    assert!(code.contains("BitcoinHtlc"));
    assert!(code.contains("RandomWalkVerification"));
    assert!(code.contains("VaultLifecycle"));
    assert!(code.contains("pub fn create_vault"));
    assert!(code.contains("pub fn unlock_vault"));
    assert!(code.contains("pub fn check_lifecycle"));
    // invariants
    assert!(
        !code.contains("duration_seconds"),
        "Invariant #4: no wall-clock"
    );
    assert!(!code.contains("TimeLock"), "Invariant #4: no TimeLock");
    assert!(!code.contains("serde_json"), "Invariant #2: no serde_json");
    assert!(
        !code.contains("lock_conditions"),
        "Invariant: old API absent"
    );
    Ok(())
}

#[test]
fn test_vault_generation_typescript() -> Result<(), Box<dyn std::error::Error>> {
    let spec = DsmSpecification::Vault(multi_sig_vault_spec());
    let generator = TypeScriptGenerator::new(true, true);
    let code = generator.generate(&spec)?;

    assert!(code.contains("auto-generated by dsm-gen"));
    assert!(code.contains("MultiSigVaultClient"));
    assert!(code.contains("FulfillmentCondition"));
    assert!(code.contains("bitcoin_htlc"));
    assert!(code.contains("multi_signature"));
    assert!(code.contains("VaultLifecycle"));
    // invariants
    assert!(
        !code.contains("duration_seconds"),
        "Invariant #4: no wall-clock"
    );
    assert!(!code.contains("TimeLock"), "Invariant #4: no TimeLock");
    assert!(
        !code.contains("JSON.stringify"),
        "Invariant #2: no JSON.stringify"
    );
    assert!(!code.contains("JSON.parse"), "Invariant #2: no JSON.parse");
    assert!(
        !code.contains("lockConditions"),
        "Invariant: old API absent"
    );
    Ok(())
}

#[test]
fn test_vault_generation_kotlin() -> Result<(), Box<dyn std::error::Error>> {
    let spec = DsmSpecification::Vault(multi_sig_vault_spec());
    let generator = KotlinGenerator::new(true, true);
    let code = generator.generate(&spec)?;

    assert!(code.contains("auto-generated by dsm-gen"));
    assert!(code.contains("MultiSigVaultClient"));
    assert!(code.contains("sealed class FulfillmentCondition"));
    assert!(code.contains("BitcoinHtlc"));
    assert!(code.contains("VaultLifecycle"));
    // invariants
    assert!(
        !code.contains("duration_seconds"),
        "Invariant #4: no wall-clock"
    );
    assert!(!code.contains("TimeLock"), "Invariant #4: no TimeLock");
    assert!(!code.contains("Gson"), "Invariant #2: no Gson");
    assert!(
        !code.contains("lockConditions"),
        "Invariant: old API absent"
    );
    Ok(())
}

#[test]
fn test_vault_generation_swift() -> Result<(), Box<dyn std::error::Error>> {
    let spec = DsmSpecification::Vault(multi_sig_vault_spec());
    let generator = SwiftGenerator::new(true, true);
    let code = generator.generate(&spec)?;

    assert!(code.contains("auto-generated by dsm-gen"));
    assert!(code.contains("MultiSigVaultClient"));
    assert!(code.contains("indirect enum FulfillmentCondition"));
    assert!(code.contains("bitcoinHtlc"));
    assert!(code.contains("VaultLifecycle"));
    // invariants
    assert!(
        !code.contains("duration_seconds"),
        "Invariant #4: no wall-clock"
    );
    assert!(!code.contains("TimeLock"), "Invariant #4: no TimeLock");
    assert!(!code.contains("try!"), "No force-unwrap");
    assert!(
        !code.contains("lockConditions"),
        "Invariant: old API absent"
    );
    Ok(())
}

// ------------------------------------------------------------------
// Bitcoin HTLC variant – spot-check all four languages emit the type
// ------------------------------------------------------------------
#[test]
fn test_bitcoin_htlc_variant_all_languages() -> Result<(), Box<dyn std::error::Error>> {
    use dsm_gen::schema::{BitcoinHtlcSpec, BitcoinNetwork};

    let vault_spec = VaultSpecification {
        name: "BtcHtlcVault".to_string(),
        version: "1.0.0".to_string(),
        description: None,
        fulfillment_condition: FulfillmentConditionSpec::BitcoinHtlc(BitcoinHtlcSpec {
            hash_lock: "HASHLOCK11111111111111111111111111111111111111111111".to_string(),
            refund_hash_lock: "REFUNDLOCK111111111111111111111111111111111111111".to_string(),
            refund_iterations: 100,
            bitcoin_pubkey: "BTCPUBKEY1111111111111111111111111111111111111111111".to_string(),
            expected_btc_amount_sats: 100_000,
            network: BitcoinNetwork::Testnet,
            min_confirmations: 100,
        }),
        assets: vec![],
        tick_lock: None,
        recovery: None,
        metadata: None,
    };
    let spec = DsmSpecification::Vault(vault_spec);

    let rs = RustGenerator::new(false, false).generate(&spec)?;
    assert!(rs.contains("BitcoinHtlc"));
    assert!(!rs.contains("duration_seconds"));

    let ts = TypeScriptGenerator::new(false, false).generate(&spec)?;
    assert!(ts.contains("bitcoin_htlc"));

    let kt = KotlinGenerator::new(false, false).generate(&spec)?;
    assert!(kt.contains("BitcoinHtlc"));

    let sw = SwiftGenerator::new(false, false).generate(&spec)?;
    assert!(sw.contains("bitcoinHtlc"));
    Ok(())
}
