#!/bin/bash

# Build script for protobuf code generation across Rust and Android
set -e

echo "🔧 Building protobuf definitions..."

# Build Rust protobuf code
echo "📦 Building Rust protobuf code..."
cd dsm_client/deterministic_state_machine/dsm
# Proto code is generated by build scripts (dsm_sdk) from the single source of truth:
#   /proto/dsm_app.proto
# There is no standalone `proto` feature on the `dsm` crate; generation happens when building `dsm_sdk`.
cargo build -p dsm_sdk --locked
cd - > /dev/null

# Build Android protobuf code
echo "📱 Building Android protobuf code..."
cd dsm_client/android
echo "📱 Android proto generation: skipped (no Gradle protobuf plugin configured)"
echo "   Android consumes the shared schema via Rust + the WebView TS bundle."
echo "   If you later add the protobuf Gradle plugin, wire generation here."
cd - > /dev/null

echo "✅ Protobuf code generation completed!"
echo ""
echo "Generated files:"
echo "  - Rust: dsm_client/deterministic_state_machine/target/*/build/*/out/dsm.rs (via prost, OUT_DIR)"
echo "  - TypeScript: dsm_client/new_frontend/src/proto/dsm_app_pb.ts (via npm run proto:gen)"
echo "  - Android: (skipped; bytes-only JNI/WebView transport; no generated protobuf sources)"
