//! TLA+ Model Checker Runner
//!
//! Shells out to TLC (the TLA+ model checker) via `java -cp tla2tools.jar tlc2.TLC`
//! and parses stdout/stderr to produce structured verification results.
//!
//! The runner executes each spec+config pair sequentially, captures output, and
//! extracts: states generated, distinct states, search depth, and pass/fail verdict.
//!
//! This module does not modify the core `dsm` crate. It operates purely as an
//! external tool that invokes TLC as a subprocess.

use std::path::{Path, PathBuf};

use anyhow::{bail, Context};
use regex::Regex;
use serde::Serialize;

use crate::tla_trace_replay::{
    replay_trace_file, replay_trace_into_implementation, simulation_profile_for_spec,
    TlaImplementationReplayResult, TlaTraceReplayResult,
};

/// Configuration for a single TLA+ model check run.
#[derive(Debug, Clone, Serialize)]
pub struct TlaSpec {
    /// Human-readable label (e.g., "DSM_tiny")
    pub label: String,
    /// Filename of the .tla spec (relative to tla/ directory)
    pub spec_file: String,
    /// Filename of the .cfg config (relative to tla/ directory)
    pub config_file: String,
    /// Key invariants being checked (for reporting)
    pub invariants: Vec<String>,
    /// Temporal properties being checked (for reporting)
    pub properties: Vec<String>,
    /// Real-code traces linked to this spec for integrated validation.
    pub linked_implementation_traces: Vec<String>,
    /// Whether this spec supports TLC trace replay into Rust shadow models.
    pub supports_trace_replay: bool,
}

/// Structured result from parsing TLC stdout.
#[derive(Debug, Clone, Serialize)]
pub struct TlcResult {
    /// Whether model checking passed with no errors
    pub passed: bool,
    /// Total states generated by TLC
    pub states_generated: u64,
    /// Distinct states found
    pub distinct_states: u64,
    /// Depth of the complete state graph search
    pub depth_reached: u64,
    /// Error messages (empty if passed)
    pub errors: Vec<String>,
    /// Full TLC stdout (retained for debugging when verbose output is needed)
    #[serde(skip)]
    #[allow(dead_code)]
    pub raw_stdout: String,
    /// Full TLC stderr (retained for debugging when verbose output is needed)
    #[serde(skip)]
    #[allow(dead_code)]
    pub raw_stderr: String,
}

/// Runner that invokes TLC model checker on TLA+ specifications.
pub struct TlaRunner {
    /// Path to the tla/ directory containing specs, configs, and tla2tools.jar
    tla_dir: PathBuf,
    /// Path to tla2tools.jar
    jar_path: PathBuf,
}

impl TlaRunner {
    /// Create a new TLA+ runner.
    ///
    /// `project_root` is the DSM repository root (contains `tla/` directory).
    /// Verifies that `tla2tools.jar` exists before returning.
    pub fn new(project_root: &Path) -> anyhow::Result<Self> {
        let tla_dir = project_root.join("tla");
        let jar_path = tla_dir.join("tla2tools.jar");

        if !jar_path.exists() {
            bail!(
                "tla2tools.jar not found at {}. Download from: \
                 https://github.com/tlaplus/tlaplus/releases",
                jar_path.display()
            );
        }

        if !tla_dir.join("DSM.tla").exists() {
            bail!("DSM.tla not found in {}", tla_dir.display());
        }

        Ok(Self { tla_dir, jar_path })
    }

    /// Run a single spec+config pair and return structured results.
    pub async fn run_spec(&self, spec: &TlaSpec) -> anyhow::Result<TlcResult> {
        let spec_path = self.tla_dir.join(&spec.spec_file);
        let config_path = self.tla_dir.join(&spec.config_file);

        if !spec_path.exists() {
            bail!("Spec file not found: {}", spec_path.display());
        }
        if !config_path.exists() {
            bail!("Config file not found: {}", config_path.display());
        }

        // Create a unique working directory for this run
        let work_dir = self
            .tla_dir
            .join("states")
            .join(format!("vv_{}", spec.label));
        tokio::fs::create_dir_all(&work_dir)
            .await
            .context("Failed to create TLC working directory")?;

        // Build TLC command following run_tlc.sh pattern
        let output = tokio::process::Command::new("java")
            .arg("-XX:+UseParallelGC")
            .arg("-cp")
            .arg(&self.jar_path)
            .arg("tlc2.TLC")
            .arg("-workers")
            .arg("auto")
            .arg("-checkpoint")
            .arg("0")
            .arg("-metadir")
            .arg(&work_dir)
            .arg("-config")
            .arg(&spec.config_file)
            .arg(&spec.spec_file)
            .current_dir(&self.tla_dir)
            .output()
            .await
            .context("Failed to spawn TLC process (is java installed?)")?;

        let stdout = String::from_utf8_lossy(&output.stdout).to_string();
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();

        Ok(parse_tlc_output(&stdout, &stderr))
    }

    async fn generate_trace_file(&self, spec: &TlaSpec) -> anyhow::Result<PathBuf> {
        let profile = simulation_profile_for_spec(spec);
        let replay_dir = self
            .tla_dir
            .join("states")
            .join(format!("trace_replay_{}", spec.label.to_lowercase()));
        tokio::fs::create_dir_all(&replay_dir)
            .await
            .context("Failed to create TLC trace replay directory")?;

        let trace_prefix = replay_dir.join("trace");
        let trace_file = PathBuf::from(format!("{}_0_0", trace_prefix.display()));
        if trace_file.exists() {
            let _ = tokio::fs::remove_file(&trace_file).await;
        }

        let simulate_arg = format!(
            "num=1,file={}",
            trace_prefix
                .strip_prefix(&self.tla_dir)
                .unwrap_or(&trace_prefix)
                .display()
        );

        let output = tokio::process::Command::new("java")
            .arg("-XX:+UseParallelGC")
            .arg("-cp")
            .arg(&self.jar_path)
            .arg("tlc2.TLC")
            .arg("-deadlock")
            .arg("-workers")
            .arg("1")
            .arg("-checkpoint")
            .arg("0")
            .arg("-depth")
            .arg(profile.depth.to_string())
            .arg("-simulate")
            .arg(simulate_arg)
            .arg("-seed")
            .arg(profile.seed.to_string())
            .arg("-config")
            .arg(&spec.config_file)
            .arg(&spec.spec_file)
            .current_dir(&self.tla_dir)
            .output()
            .await
            .context("Failed to spawn TLC simulation for literal trace replay")?;

        if !output.status.success() {
            let stdout = String::from_utf8_lossy(&output.stdout);
            let stderr = String::from_utf8_lossy(&output.stderr);
            bail!(
                "TLC simulation failed for {}.\nstdout:\n{}\nstderr:\n{}",
                spec.label,
                stdout,
                stderr
            );
        }

        if !trace_file.exists() {
            bail!(
                "TLC simulation for {} completed without writing {}",
                spec.label,
                trace_file.display()
            );
        }

        Ok(trace_file)
    }

    /// Generate one deterministic TLC simulation trace and run both replay layers over it.
    pub async fn run_integrated_trace_replays(
        &self,
        spec: &TlaSpec,
    ) -> anyhow::Result<(TlaTraceReplayResult, TlaImplementationReplayResult)> {
        let trace_file = self.generate_trace_file(spec).await?;
        let literal = replay_trace_file(spec, &trace_file)?;
        let implementation = replay_trace_into_implementation(spec, &trace_file)?;
        Ok((literal, implementation))
    }

    /// Generate a deterministic TLC simulation trace and replay it inside Rust.
    #[allow(dead_code)]
    pub async fn run_literal_trace_replay(
        &self,
        spec: &TlaSpec,
    ) -> anyhow::Result<TlaTraceReplayResult> {
        Ok(self.run_integrated_trace_replays(spec).await?.0)
    }

    /// Generate a deterministic TLC simulation trace and replay it against actual DSM code.
    #[allow(dead_code)]
    pub async fn run_implementation_trace_replay(
        &self,
        spec: &TlaSpec,
    ) -> anyhow::Result<TlaImplementationReplayResult> {
        Ok(self.run_integrated_trace_replays(spec).await?.1)
    }

    /// Return the standard set of specs to run for vertical validation.
    pub fn standard_specs() -> Vec<TlaSpec> {
        vec![
            TlaSpec {
                label: "DSM_tiny".into(),
                spec_file: "DSM.tla".into(),
                config_file: "DSM_tiny.cfg".into(),
                invariants: vec![
                    "TypeInvariant".into(),
                    "DJTESafety".into(),
                    "ConcreteRefinesAbstract".into(),
                    "RefinementStrengthening".into(),
                    "SourceVaultBounded".into(),
                ],
                properties: vec![],
                linked_implementation_traces: vec![
                    "state_machine_transfer_chain".into(),
                    "state_machine_signature_rejection".into(),
                    "bilateral_precommit_tripwire".into(),
                    "bilateral_precomputed_finalize_hash".into(),
                    "djte_emission_happy_path".into(),
                    "djte_repeated_emission_alignment".into(),
                    "djte_supply_underflow_rejection".into(),
                    "dlv_manager_inventory_consistency".into(),
                    "token_manager_balance_replay".into(),
                    "token_manager_overspend_rejection".into(),
                ],
                supports_trace_replay: true,
            },
            TlaSpec {
                label: "DSM_small".into(),
                spec_file: "DSM.tla".into(),
                config_file: "DSM_small.cfg".into(),
                invariants: vec![
                    "TypeInvariant".into(),
                    "DJTESafety".into(),
                    "ConcreteRefinesAbstract".into(),
                    "RefinementStrengthening".into(),
                ],
                properties: vec![
                    "SpentJapsNeverShrink".into(),
                    "CommitNeverDecreasesConcrete".into(),
                    "SourceRemainingNeverIncreases".into(),
                ],
                linked_implementation_traces: vec![
                    "state_machine_transfer_chain".into(),
                    "state_machine_signature_rejection".into(),
                    "bilateral_precommit_tripwire".into(),
                    "bilateral_precomputed_finalize_hash".into(),
                    "djte_emission_happy_path".into(),
                    "djte_supply_underflow_rejection".into(),
                    "dlv_manager_inventory_consistency".into(),
                    "token_manager_balance_replay".into(),
                    "token_manager_overspend_rejection".into(),
                ],
                supports_trace_replay: true,
            },
            TlaSpec {
                label: "DSM_system".into(),
                spec_file: "DSM.tla".into(),
                config_file: "DSM_system_bounded.cfg".into(),
                invariants: vec![
                    "TypeInvariant".into(),
                    "DJTESafety".into(),
                    "ConcreteRefinesAbstract".into(),
                    "RefinementStrengthening".into(),
                ],
                properties: vec![
                    "SpentJapsNeverShrink".into(),
                    "CommitNeverDecreasesConcrete".into(),
                    "SourceRemainingNeverIncreases".into(),
                ],
                linked_implementation_traces: vec![
                    "state_machine_transfer_chain".into(),
                    "state_machine_signature_rejection".into(),
                    "bilateral_precommit_tripwire".into(),
                    "bilateral_precomputed_finalize_hash".into(),
                    "djte_emission_happy_path".into(),
                    "djte_supply_underflow_rejection".into(),
                    "dlv_manager_inventory_consistency".into(),
                    "token_manager_balance_replay".into(),
                    "token_manager_overspend_rejection".into(),
                ],
                supports_trace_replay: true,
            },
            TlaSpec {
                label: "Tripwire".into(),
                spec_file: "DSM_Tripwire.tla".into(),
                config_file: "DSM_Tripwire.cfg".into(),
                invariants: vec!["TripwireInvariant".into()],
                properties: vec![],
                linked_implementation_traces: vec![
                    "tripwire_parent_consumption".into(),
                    "receipt_verifier_tripwire".into(),
                    "bilateral_precommit_tripwire".into(),
                    "bilateral_precomputed_finalize_hash".into(),
                ],
                supports_trace_replay: true,
            },
            // --- Offline Finality (Paper Theorems 4.1, 4.2) ---
            // Bilateral settlement irreversibility + BLE partition tolerance.
            TlaSpec {
                label: "OfflineFinality".into(),
                spec_file: "DSM_OfflineFinality.tla".into(),
                config_file: "DSM_OfflineFinality.cfg".into(),
                invariants: vec![
                    "TypeOK".into(),
                    "BilateralIrreversibility".into(),
                    "FullSettlement".into(),
                    "NoHalfCommit".into(),
                    "TripwireGuaranteesUniqueness".into(),
                    "TokenConservation".into(),
                    "BalancesNonNegative".into(),
                ],
                properties: vec![],
                linked_implementation_traces: vec!["bilateral_full_offline_finality".into()],
                // No literal TLC trace replay (no simulation trace file);
                // linked implementation traces provide the code-level bridge.
                supports_trace_replay: false,
            },
            // --- Non-Interference (Paper Lemma 3.1, 3.2, Theorem 3.1) ---
            // Additive scaling: operations on one bilateral pair cannot affect
            // any other pair. Mathematical core of Θ(N) throughput.
            TlaSpec {
                label: "NonInterference".into(),
                spec_file: "DSM_NonInterference.tla".into(),
                config_file: "DSM_NonInterference.cfg".into(),
                invariants: vec![
                    "TypeOK".into(),
                    "NonInterference".into(),
                    "PairIsolation".into(),
                    "PerPairConservation".into(),
                    "ZeroRefreshForInactive".into(),
                ],
                properties: vec![],
                linked_implementation_traces: vec!["bilateral_pair_non_interference".into()],
                supports_trace_replay: false,
            },
        ]
    }

    /// Return the opt-in specs that deepen TLA coverage but are not part of the
    /// default fast validation gate.
    pub fn extended_specs() -> Vec<TlaSpec> {
        vec![
            TlaSpec {
                label: "DSM_extended".into(),
                spec_file: "DSM.tla".into(),
                config_file: "DSM_extended.cfg".into(),
                invariants: vec![
                    "TypeInvariant".into(),
                    "DJTESafety".into(),
                    "ConcreteRefinesAbstract".into(),
                    "RefinementStrengthening".into(),
                    "SourceVaultBounded".into(),
                ],
                properties: vec![
                    "SpentJapsNeverShrink".into(),
                    "CommitNeverDecreasesConcrete".into(),
                    "SourceRemainingNeverIncreases".into(),
                ],
                linked_implementation_traces: vec![
                    "state_machine_transfer_chain".into(),
                    "state_machine_signature_rejection".into(),
                    "bilateral_precommit_tripwire".into(),
                    "bilateral_precomputed_finalize_hash".into(),
                    "djte_emission_happy_path".into(),
                    "djte_supply_underflow_rejection".into(),
                    "dlv_manager_inventory_consistency".into(),
                    "token_manager_balance_replay".into(),
                    "token_manager_overspend_rejection".into(),
                ],
                supports_trace_replay: true,
            },
            TlaSpec {
                label: "DSM_bilateral_liveness".into(),
                spec_file: "DSM_BilateralLiveness.tla".into(),
                config_file: "DSM_BilateralLiveness.cfg".into(),
                invariants: vec![
                    "TypeOK".into(),
                    "NoFork".into(),
                    "TokenConservation".into(),
                    "ModalLockConsistency".into(),
                    "BalancesNonNegative".into(),
                ],
                properties: vec![
                    "SessionTermination".into(),
                    "ModalLockResolution".into(),
                    "DLVLiveness".into(),
                ],
                linked_implementation_traces: vec![],
                supports_trace_replay: false,
            },
        ]
    }

    /// Run all standard specs sequentially and return results.
    pub async fn run_all(
        &self,
        include_liveness: bool,
    ) -> anyhow::Result<Vec<(TlaSpec, TlcResult)>> {
        let mut specs = Self::standard_specs();
        if include_liveness {
            specs.extend(Self::extended_specs());
        }
        let mut results = Vec::with_capacity(specs.len());

        for spec in specs {
            eprintln!("  Running TLC: {} ({}) ...", spec.label, spec.config_file);
            let result = self.run_spec(&spec).await?;
            let verdict = if result.passed { "PASSED" } else { "FAILED" };
            eprintln!(
                "    {} ({} states, {} distinct, depth {})",
                verdict, result.states_generated, result.distinct_states, result.depth_reached
            );
            results.push((spec, result));
        }

        Ok(results)
    }
}

/// Parse TLC stdout/stderr to extract structured metrics.
fn parse_tlc_output(stdout: &str, stderr: &str) -> TlcResult {
    let combined = if stderr.is_empty() {
        stdout.to_string()
    } else if stdout.is_empty() {
        stderr.to_string()
    } else {
        format!("{stdout}\n{stderr}")
    };
    let mut passed = false;
    let mut states_generated: u64 = 0;
    let mut distinct_states: u64 = 0;
    let mut depth_reached: u64 = 0;
    let mut errors = Vec::new();

    // Check for successful completion
    if combined.contains("Model checking completed. No error has been found") {
        passed = true;
    }

    // Parse state counts: "X states generated (Y s), Z distinct states found"
    // TLC may emit this in different formats; handle both
    let states_re = Regex::new(r"(\d[\d,]*)\s+states generated").ok();
    let distinct_re = Regex::new(r"(\d[\d,]*)\s+distinct states found").ok();
    let depth_re = Regex::new(r"(?i)depth\s+of\s+the\s+complete\s+state\s+graph.*?is\s+(\d+)").ok();

    if let Some(ref re) = states_re {
        for caps in re.captures_iter(&combined) {
            states_generated = parse_number_with_commas(&caps[1]);
        }
    }

    if let Some(ref re) = distinct_re {
        for caps in re.captures_iter(&combined) {
            distinct_states = parse_number_with_commas(&caps[1]);
        }
    }

    if let Some(ref re) = depth_re {
        for caps in re.captures_iter(&combined) {
            if let Ok(d) = caps[1].parse() {
                depth_reached = d;
            }
        }
    }

    // Check for errors
    let error_re = Regex::new(r"(?m)^Error:\s*(.+)$").ok();
    let invariant_re = Regex::new(r"Invariant\s+(\S+)\s+is\s+violated").ok();
    let exception_re = Regex::new(r"(?m)^The exception was a\s+(.+)$").ok();

    let mut push_error = |msg: String| {
        if !errors.contains(&msg) {
            errors.push(msg);
        }
    };

    if let Some(ref re) = error_re {
        for caps in re.captures_iter(&combined) {
            push_error(caps[1].trim().to_string());
            passed = false;
        }
    }

    if let Some(ref re) = invariant_re {
        for caps in re.captures_iter(&combined) {
            push_error(format!("Invariant violated: {}", &caps[1]));
            passed = false;
        }
    }

    if let Some(ref re) = exception_re {
        for caps in re.captures_iter(&combined) {
            push_error(format!("TLC exception: {}", caps[1].trim()));
            passed = false;
        }
    }

    for line in combined.lines() {
        if let Some(cause) = line.strip_prefix(':') {
            let cause = cause.trim();
            if !cause.is_empty() {
                push_error(format!("TLC cause: {cause}"));
                passed = false;
            }
        }
    }

    TlcResult {
        passed,
        states_generated,
        distinct_states,
        depth_reached,
        errors,
        raw_stdout: stdout.to_string(),
        raw_stderr: stderr.to_string(),
    }
}

/// Parse a number that may contain comma separators (e.g., "1,234,567").
fn parse_number_with_commas(s: &str) -> u64 {
    s.replace(',', "").parse().unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_successful_output() {
        let stdout = r#"
TLC2 Version 2.18 of Day Month 20XX (rev: abc123)
Running breadth-first search Model-Checking with fp 42 and seed 123456789
Computed 1 initial states.
Progress(10) at 2025-01-01 00:00:00: 12,487 states generated (6,244 s/min), 3,201 distinct states found (1,601 ds/min), 0 states left on queue.
Checkpointing of run states/vv_test
Model checking completed. No error has been found.
12,487 states generated, 3,201 distinct states found, 0 states left on queue.
The depth of the complete state graph search is 10.
Finished in 02s at (2025-01-01 00:00:02)
"#;

        let result = parse_tlc_output(stdout, "");
        assert!(result.passed);
        assert_eq!(result.states_generated, 12487);
        assert_eq!(result.distinct_states, 3201);
        assert_eq!(result.depth_reached, 10);
        assert!(result.errors.is_empty());
    }

    #[test]
    fn parse_uses_last_state_counts_when_tlc_reports_progress_and_final_totals() {
        let stdout = r#"
Progress(8) at 2026-03-15 06:40:07: 91,113 states generated, 26,855 distinct states found, 14,354 states left on queue.
Progress(24) at 2026-03-15 06:55:03: 13,884,633 states generated, 2,188,440 distinct states found, 0 states left on queue.
Checking 3 branches of temporal properties for the complete state space with 6,565,320 total distinct states at (2026-03-15 06:55:03)
Model checking completed. No error has been found.
13,884,633 states generated, 2,188,440 distinct states found, 0 states left on queue.
The depth of the complete state graph search is 24.
"#;

        let result = parse_tlc_output(stdout, "");
        assert!(result.passed);
        assert_eq!(result.states_generated, 13_884_633);
        assert_eq!(result.distinct_states, 2_188_440);
        assert_eq!(result.depth_reached, 24);
    }

    #[test]
    fn parse_invariant_violation() {
        let stdout = r#"
Error: Invariant TripwireInvariant is violated.
100 states generated, 50 distinct states found.
The depth of the complete state graph search is 5.
"#;
        let result = parse_tlc_output(stdout, "");
        assert!(!result.passed);
        assert!(!result.errors.is_empty());
    }

    #[test]
    fn parse_exception_cause_from_stderr() {
        let stderr = r#"
Error: TLC threw an unexpected exception.
The exception was a java.util.concurrent.ExecutionException
: java.rmi.server.ExportException: Listen failed on port: 0
"#;
        let result = parse_tlc_output("", stderr);
        assert!(!result.passed);
        assert!(result
            .errors
            .iter()
            .any(|err| err.contains("java.util.concurrent.ExecutionException")));
        assert!(result
            .errors
            .iter()
            .any(|err| err.contains("Listen failed on port: 0")));
    }
}
