// auto-generated by dsm-gen v1.0.0 — DO NOT EDIT
// This file was automatically generated from a DSM specification.
// For more information about DSM, visit: https://github.com/dsm-project

import { DsmSdk, DeviceId, Hash256, StateTransition } from '@dsm/sdk'

// ---- Fulfillment condition types for SimpleEscrow ----
// Mirrors FulfillmentMechanism oneof in dsm_app.proto.
// Proto tag 1 (time_release) is absent — DSM is clockless.

export interface PaymentCondition {
amount: bigint;
tokenId: string;
recipient: string;          // Base32 Crockford device_id
verificationState: Uint8Array; // BLAKE3-256 reference state hash
}

export interface CryptoConditionParams {
conditionHash: Uint8Array;  // BLAKE3("DSM/crypto-condition\0" || preimage)
publicParams: Uint8Array;
}

export interface MultiSignatureParams {
publicKeys: Uint8Array[];   // SPHINCS+ public keys
threshold: number;
}

export interface StateReferenceParams {
referenceStates: Uint8Array[]; // BLAKE3-256 hashes
parameters: Uint8Array;
}

export interface RandomWalkParams {
verificationKey: Uint8Array;
statement: string;
}

export interface BitcoinHtlcParams {
hashLock: Uint8Array;          // 32 bytes: SHA256(sk_V)
refundHashLock: Uint8Array;    // 32 bytes: SHA256(rk_V)
refundIterations: bigint;      // DSM chain-tick count (not wall time)
bitcoinPubkey: Uint8Array;     // 33 bytes: compressed pubkey
expectedBtcAmountSats: bigint;
network: 0 | 1 | 2;           // 0=mainnet 1=testnet 2=signet
minConfirmations: bigint;      // canonical=100 (dBTC §6.4)
}

/** Recursive AND/OR wrappers */
export interface AndCondition { conditions: FulfillmentCondition[]; }
export interface OrCondition  { conditions: FulfillmentCondition[]; }

/** Discriminated union — field "type" selects the active variant. */
export type FulfillmentCondition =
| { type: 'payment';                  payment:                PaymentCondition }
| { type: 'crypto_condition';         cryptoCondition:        CryptoConditionParams }
| { type: 'multi_signature';          multiSignature:         MultiSignatureParams }
| { type: 'state_reference';          stateReference:         StateReferenceParams }
| { type: 'random_walk_verification'; randomWalkVerification: RandomWalkParams }
| { type: 'bitcoin_htlc';             bitcoinHtlc:            BitcoinHtlcParams }
| { type: 'and';                      and:                    AndCondition }
| { type: 'or';                       or:                     OrCondition };

// ---- Vault configuration ----

export interface AssetDefinition {
assetId: string;
amount: bigint;
/** Base32 Crockford BLAKE3-256 for chain-anchored balance */
chainStateHash?: string;
chainStateNumber?: bigint;
metadata?: Record<string, string>;
}

export interface CreateCfg {
assets: AssetDefinition[];
fulfillmentCondition: FulfillmentCondition;
tickLock?: TickLockConfig;
recovery?: RecoveryConfig;
}

export interface TickLockConfig {
durationIterations: bigint;
action: 'return_to_owner' | { type: 'release_to_recipient'; recipient: string } | 'burn';
}

export interface RecoveryConfig {
mechanism:
| { type: 'multi_sig_recovery'; requiredSignatures: number; recoveryKeys: string[] }
| { type: 'social_recovery'; trustees: string[]; threshold: number };
}

export interface UnlockProof {
// Provide the proof matching the vault's fulfillment condition.
conditionProof: Uint8Array;
signature: Uint8Array;
}

export type VaultLifecycle = 'limbo' | 'active' | 'unlocked' | 'claimed' | 'invalidated';

export interface VaultStatus {
id: Hash256;
lifecycle: VaultLifecycle;
assets: AssetDefinition[];
fulfillmentCondition: FulfillmentCondition;
createdAtState: bigint;
unlockedAtState?: bigint;
}

export interface VaultMetadata {
name: string;
version: string;
description?: string;
creator: DeviceId;
hash: Hash256;
}

/**
 * Client for SimpleEscrow Vault
 * Payment-locked escrow vault — Bob proves payment to Alice to unlock
 */
export class SimpleEscrowVaultClient {
  constructor(
    private readonly sdk: DsmSdk,
    private readonly vaultId?: Hash256
  ) {}

  /* ------------ Creation ------------ */
  
  /**
   * Create a new SimpleEscrow vault
   */
  static async create(sdk: DsmSdk, cfg: CreateCfg): Promise<SimpleEscrowVaultClient> {
    if (!cfg.assets || cfg.assets.length === 0) {
      throw new Error('At least one asset must be specified');
    }
    if (!cfg.fulfillmentCondition) {
      throw new Error('fulfillmentCondition must be specified');
    }
    
    // Create vault through DSM SDK
    const vaultId = await sdk.vault.create({
      assets: cfg.assets,
      fulfillmentCondition: cfg.fulfillmentCondition,
      tickLock: cfg.tickLock,
      recovery: cfg.recovery,
    });
    
    return new SimpleEscrowVaultClient(sdk, vaultId);
  }

  /* ------------ Getters ------------ */
  
  /**
   * Get current vault status
   */
  async status(): Promise<VaultStatus> {
    if (!this.vaultId) {
      throw new Error('Vault not initialized');
    }
    
    return await this.sdk.vault.status(this.vaultId);
  }

  /**
   * Get vault metadata
   */
  async metadata(): Promise<VaultMetadata> {
    if (!this.vaultId) {
      throw new Error('Vault not initialized');
    }
    
    return await this.sdk.vault.metadata(this.vaultId);
  }

  /**
   * Get vault ID
   */
  getId(): Hash256 | undefined {
    return this.vaultId;
  }

  /* ------------ Actions ------------ */
  
  /**
   * Unlock the vault with a fulfillment proof.
   * The proof must satisfy the vault's FulfillmentCondition.
   */
  async unlock(proof: UnlockProof): Promise<StateTransition> {
    if (!this.vaultId) {
      throw new Error('Vault not initialized — call create() first');
    }
    await this.validateUnlockProof(proof);
    return await this.sdk.vault.unlock(this.vaultId, proof);
  }

  /**
   * Check if a proof satisfies the vault's fulfillment condition.
   */
  async canUnlock(proof: UnlockProof): Promise<boolean> {
    try {
      await this.validateUnlockProof(proof);
      return true;
    } catch {
      return false;
    }
  }

  /* ------------ Private Methods ------------ */
  
  private async validateUnlockProof(proof: UnlockProof): Promise<void> {
    const status = await this.status();

    if (status.lifecycle === 'unlocked' || status.lifecycle === 'claimed') {
      throw new Error(`Vault is already ${status.lifecycle}`);
    }
    if (status.lifecycle === 'invalidated') {
      throw new Error('Vault has been invalidated');
    }

    // Condition-specific validation — delegates final proof verification to SDK.
    const cond = status.fulfillmentCondition;
    switch (cond.type) {
      case 'payment':
      case 'crypto_condition':
      case 'state_reference':
      case 'random_walk_verification':
      case 'bitcoin_htlc':
        if (!proof.conditionProof || proof.conditionProof.length === 0) {
          throw new Error(`conditionProof required for ${cond.type} unlock`);
        }
        break;
      case 'multi_signature':
        if (!proof.conditionProof || proof.conditionProof.length === 0) {
          throw new Error('conditionProof (serialised multi-sig bundle) required');
        }
        break;
      case 'and':
      case 'or':
        // Composite conditions — proof bundle validated by the SDK
        if (!proof.conditionProof || proof.conditionProof.length === 0) {
          throw new Error(`conditionProof required for composite (${cond.type}) unlock`);
        }
        break;
    }
  }
}

