// auto-generated by dsm-gen v1.0.0 — DO NOT EDIT
// This file was automatically generated from a DSM specification.
// For more information about DSM, visit: https://github.com/dsm-project

import { DsmSdk, DeviceId, Hash256, StateTransition } from '@dsm/sdk'

// Configuration types for LoanVault
export interface CreateCfg {
assets: AssetDefinition[];
lockConditions: LockConditions;
timeout?: TimeoutConfig;
recovery?: RecoveryConfig;
}

export interface AssetDefinition {
assetId: string;
amount: number;
metadata?: Record<string, any>;
}

export interface LockConditions {
conditionType: 'multi_sig' | 'time_lock' | 'hash_lock' | 'repayment_confirmation' | 'custom' | 'composite';
parameters: Record<string, any>;
}

export interface TimeoutConfig {
durationSeconds: number;
timeoutAction: 'return_to_owner' | { release_to_address: { address: string } } | 'burn';
}

export interface RecoveryConfig {
mechanism: 'multi_sig_recovery' | 'time_delayed_recovery' | 'social_recovery';
parameters: Record<string, any>;
}

export interface UnlockParams {
// Parameters needed to unlock the vault based on lock conditions
signatures?: string[];
preimage?: string;
proof?: any;
}

export interface VaultStatus {
id: Hash256;
isLocked: boolean;
assets: AssetDefinition[];
lockConditions: LockConditions;
createdAt: string;
unlockedAt?: string;
}

export interface VaultMetadata {
name: string;
version: string;
description?: string;
creator: DeviceId;
hash: Hash256;
}

/**
 * Client for LoanVault Vault
 * A vault that holds collateral for a loan until repayment is confirmed
 */
export class LoanVaultVaultClient {
  constructor(
    private readonly sdk: DsmSdk,
    private readonly vaultId?: Hash256
  ) {}

  /* ------------ Creation ------------ */
  
  /**
   * Create a new LoanVault vault
   */
  static async create(sdk: DsmSdk, cfg: CreateCfg): Promise<LoanVaultVaultClient> {
    // Validate configuration
    this.validateCreateConfig(cfg);
    
    // Create vault through DSM SDK
    const vaultId = await sdk.vault.create({
      assets: cfg.assets,
      lockConditions: cfg.lockConditions,
      timeout: cfg.timeout,
      recovery: cfg.recovery,
    });
    
    return new LoanVaultVaultClient(sdk, vaultId);
  }

  /* ------------ Getters ------------ */
  
  /**
   * Get current vault status
   */
  async status(): Promise<VaultStatus> {
    if (!this.vaultId) {
      throw new Error('Vault not initialized');
    }
    
    return await this.sdk.vault.status(this.vaultId);
  }

  /**
   * Get vault metadata
   */
  async metadata(): Promise<VaultMetadata> {
    if (!this.vaultId) {
      throw new Error('Vault not initialized');
    }
    
    return await this.sdk.vault.metadata(this.vaultId);
  }

  /**
   * Get vault ID
   */
  getId(): Hash256 | undefined {
    return this.vaultId;
  }

  /* ------------ Actions ------------ */
  
  /**
   * Unlock the vault with provided parameters
   */
  async unlock(params: UnlockParams): Promise<StateTransition> {
    if (!this.vaultId) {
      throw new Error('Vault not initialized');
    }
    
    // Validate unlock parameters based on lock conditions
    await this.validateUnlockParams(params);
    
    return await this.sdk.vault.unlock(this.vaultId, params);
  }

  /**
   * Check if vault can be unlocked with given parameters
   */
  async canUnlock(params: UnlockParams): Promise<boolean> {
    try {
      await this.validateUnlockParams(params);
      return true;
    } catch {
      return false;
    }
  }

  /* ------------ Private Methods ------------ */
  
  private static validateCreateConfig(cfg: CreateCfg): void {
    if (!cfg.assets || cfg.assets.length === 0) {
      throw new Error('At least one asset must be specified');
    }
    
    for (const asset of cfg.assets) {
      if (!asset.assetId || asset.amount <= 0) {
        throw new Error('Invalid asset definition');
      }
    }
    
    if (!cfg.lockConditions) {
      throw new Error('Lock conditions must be specified');
    }
  }
  
  private async validateUnlockParams(params: UnlockParams): Promise<void> {
    const status = await this.status();
    
    if (!status.isLocked) {
      throw new Error('Vault is already unlocked');
    }
    
    // Validate based on lock condition type
    switch (status.lockConditions.conditionType) {
      case 'multi_sig':
        if (!params.signatures || params.signatures.length === 0) {
          throw new Error('Signatures required for multi-sig unlock');
        }
        break;
        
      case 'hash_lock':
        if (!params.preimage) {
          throw new Error('Preimage required for hash lock unlock');
        }
        break;
        
      case 'time_lock':
        // Time validation would be handled by the DSM SDK
        break;
        
      default:
        if (!params.proof) {
          throw new Error('Proof required for custom unlock conditions');
        }
    }
  }
}

/**
 * Factory for managing multiple LoanVault vaults
 */
export class LoanVaultVaultFactory {
  private vaults = new Map<Hash256, LoanVaultVaultClient>();

  constructor(private readonly sdk: DsmSdk) {}

  /**
   * Create a new vault and add it to the factory
   */
  async createVault(cfg: CreateCfg): Promise<LoanVaultVaultClient> {
    const vault = await LoanVaultVaultClient.create(this.sdk, cfg);
    const vaultId = vault.getId();
    
    if (vaultId) {
      this.vaults.set(vaultId, vault);
    }
    
    return vault;
  }

  /**
   * Get an existing vault by ID
   */
  getVault(vaultId: Hash256): LoanVaultVaultClient | undefined {
    return this.vaults.get(vaultId);
  }

  /**
   * List all managed vaults
   */
  listVaults(): LoanVaultVaultClient[] {
    return Array.from(this.vaults.values());
  }

  /**
   * Remove a vault from management
   */
  removeVault(vaultId: Hash256): boolean {
    return this.vaults.delete(vaultId);
  }

  /**
   * Get vault count
   */
  getVaultCount(): number {
    return this.vaults.size;
  }
}

