fn write_min_schema_hash_module() {
    use std::{
        env,
        fs::{self, File},
        io::Write,
        path::PathBuf,
    };

    let out_dir = match env::var("OUT_DIR") {
        Ok(v) => v,
        Err(_) => return,
    };

    // Locate repo root and proto dir deterministically
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| ".".into());
    let repo_root = repo_root_from_crate(&manifest_dir);
    let proto_dir = repo_root.join("proto");
    let canonical_proto = proto_dir.join("dsm_app.proto");

    // Rebuild only when canonical proto changes
    println!("cargo:rerun-if-changed={}", canonical_proto.display());

    // Hash the canonical proto file only (single source of truth)
    let mut hasher = blake3::Hasher::new();
    if let Ok(bytes) = fs::read(&canonical_proto) {
        hasher.update(&bytes);
    }
    let digest = *hasher.finalize().as_bytes(); // [u8; 32]

    // Emit accessor module
    let out_path = PathBuf::from(out_dir).join("dsm_contact_schema_hash.rs");
    if let Some(parent) = out_path.parent() {
        let _ = fs::create_dir_all(parent);
    }
    let mut f = match File::create(&out_path) {
        Ok(f) => f,
        Err(e) => {
            eprintln!("Failed to create hash module: {}", e);
            return;
        }
    };

    writeln!(f, "// Auto-generated by build.rs — DO NOT EDIT").ok();

    let mut emit = |base: &str| {
        writeln!(
            f,
            "pub fn {base}_bytes() -> [u8; 32] {{ {digest:?} }}",
            base = base,
            digest = digest
        )
        .ok();
        writeln!(
            f,
            "pub fn {base}_vec() -> ::std::vec::Vec<u8> {{ {base}_bytes().to_vec() }}",
            base = base
        )
        .ok();
    };

    for base in [
        "contact_add_response_schema_hash",
        "system_genesis_response_schema_hash",
        "balance_get_response_schema_hash",
        "wallet_history_response_schema_hash",
        "contacts_list_response_schema_hash",
        "faucet_claim_response_schema_hash",
        "online_transfer_response_schema_hash",
        "state_info_response_schema_hash",
    ] {
        emit(base);
    }
}

fn repo_root_from_crate(manifest_dir: &str) -> std::path::PathBuf {
    let mut dir = std::path::PathBuf::from(manifest_dir);
    loop {
        if dir.join("proto").is_dir() || dir.join(".git").is_dir() {
            return dir;
        }
        if !dir.pop() {
            // Fallback: if nothing found, just return the original manifest dir
            return std::path::PathBuf::from(manifest_dir);
        }
    }
}

fn sanitize_generated_prost(out_dir: &std::path::Path) {
    use std::fs;

    let generated = out_dir.join("dsm.rs");
    if !generated.exists() {
        return;
    }

    match fs::read_to_string(&generated) {
        Ok(src) => {
            // Workaround for nightly clippy ICE in MacroUseImports lint when
            // scanning parsed #[repr(i32)] attrs in prost-generated include files.
            // This does not change protobuf wire format behavior.
            let sanitized = src.replace("#[repr(i32)]\n", "");
            if sanitized != src {
                if let Err(e) = fs::write(&generated, sanitized) {
                    eprintln!(
                        "warning: failed to sanitize generated proto file {}: {}",
                        generated.display(),
                        e
                    );
                } else {
                    println!(
                        "cargo:warning=Sanitized generated proto file to avoid clippy ICE: {}",
                        generated.display()
                    );
                }
            }
        }
        Err(e) => eprintln!(
            "warning: failed to read generated proto file {}: {}",
            generated.display(),
            e
        ),
    }
}

fn main() {
    // Safety check: prevent release builds with test-only flags
    if std::env::var("PROFILE").as_deref() == Ok("release") {
        // Check if FORCE_NO_BACKEND is accessible in release builds
        // This would indicate the cfg guards were incorrectly removed
        if std::env::var("CARGO_FEATURE_test").is_ok() {
            eprintln!("ERROR: Building release with test/debug features enabled!");
            eprintln!("The FORCE_NO_BACKEND flag must not be available in release builds.");
            std::process::exit(1);
        }
    }

    // Preserve deterministic schema hash emission used by the SDK
    write_min_schema_hash_module();

    // Prefer vendored protoc to avoid system dependency differences
    if let Ok(protoc_path) = protoc_bin_vendored::protoc_bin_path() {
        std::env::set_var("PROTOC", &protoc_path);
        println!(
            "cargo:warning=dsm@0.1.0: Using vendored protoc at {}",
            protoc_path.display()
        );
    }

    // Resolve repo root and canonical proto root
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| ".".into());
    let repo_root = repo_root_from_crate(&manifest_dir);
    let proto_root = repo_root.join("proto");
    println!("cargo:rerun-if-changed={}", proto_root.display());

    // Compile canonical proto only (must match guard_protos policy)
    let canonical_proto = proto_root.join("dsm_app.proto");
    if !canonical_proto.exists() {
        eprintln!("Canonical proto not found: {}", canonical_proto.display());
        std::process::exit(1);
    }
    println!("cargo:rerun-if-changed={}", canonical_proto.display());

    // Emit a single OUT_DIR/dsm.rs include file that re-exports all packages
    if let Err(e) = tonic_build::configure()
        .build_client(false)
        .build_server(false)
        .include_file("pb.rs")
        .compile_protos(&[canonical_proto], &[proto_root.as_path()])
    {
        eprintln!("prost/tonic proto compilation failed: {}", e);
        std::process::exit(1);
    }

    if let Ok(out_dir) = std::env::var("OUT_DIR") {
        sanitize_generated_prost(std::path::Path::new(&out_dir));
    }
}
