//! Kotlin code generator for DSM specifications
//!
//! Generates type-safe Kotlin clients for DSM vaults and policies
//! with compile-time safety and Android integration.

use crate::generators::CodeGenerator;
use crate::schema::{DsmSpecification, PolicySpecification, VaultSpecification};
use anyhow::Result;

pub struct KotlinGenerator {
    include_factory: bool,
    include_test_vectors: bool,
}

impl KotlinGenerator {
    pub fn new(include_factory: bool, include_test_vectors: bool) -> Self {
        Self {
            include_factory,
            include_test_vectors,
        }
    }
}

impl CodeGenerator for KotlinGenerator {
    fn generate(&self, spec: &DsmSpecification) -> Result<String> {
        match spec {
            DsmSpecification::Vault(vault_spec) => self.generate_vault_client(vault_spec),
            DsmSpecification::Policy(policy_spec) => self.generate_policy_client(policy_spec),
        }
    }

    fn file_extension(&self) -> &'static str {
        "kt"
    }

    fn language_name(&self) -> &'static str {
        "Kotlin"
    }
}

impl KotlinGenerator {
    fn generate_header(&self) -> String {
        // Clockless/deterministic: never include wall-clock markers in generated output.
        let marker_suffix = String::new();

        format!(
            "// auto-generated by dsm-gen v{}{} — DO NOT EDIT\n\
             // This file was automatically generated from a DSM specification.\n\
             // For more information about DSM, visit: https://github.com/dsm-project\n\n",
            env!("CARGO_PKG_VERSION"),
            marker_suffix
        )
    }

    fn generate_imports(&self) -> String {
        "import java.math.BigInteger\nimport java.nio.ByteBuffer\nimport kotlin.ByteArray\n\n"
            .to_string()
    }

    fn generate_vault_client(&self, spec: &VaultSpecification) -> Result<String> {
        let mut code = String::new();

        // Header comment
        code.push_str(&self.generate_header());

        // Package declaration
        code.push_str("package com.dsm.vault.client\n\n");

        // Imports
        code.push_str(&self.generate_imports());

        // Type definitions
        code.push_str(&self.generate_vault_types(spec)?);

        // Client class
        code.push_str(&self.generate_vault_client_class(spec)?);

        // Factory class (if requested)
        if self.include_factory {
            code.push_str(&self.generate_factory_class(spec)?);
        }

        // Test vectors (if requested)
        if self.include_test_vectors {
            code.push_str(&self.generate_test_vectors()?);
        }

        Ok(code)
    }

    fn generate_policy_client(&self, spec: &PolicySpecification) -> Result<String> {
        let mut code = String::new();

        // Header comment
        code.push_str(&self.generate_header());

        // Package declaration
        code.push_str("package com.dsm.policy.client\n\n");

        // Imports
        code.push_str(&self.generate_imports());

        // Type definitions
        code.push_str(&self.generate_policy_types(spec)?);

        // Client class
        code.push_str(&self.generate_policy_client_class(spec)?);

        Ok(code)
    }

    fn generate_vault_types(&self, spec: &VaultSpecification) -> Result<String> {
        let class_name = super::base_vault_name(spec);
        let mut code = String::new();

        // FulfillmentCondition sealed class — mirrors FulfillmentMechanism oneof in dsm_app.proto.
        // Proto tag 1 (time_release) is absent: DSM is clockless (Invariant #4).
        code.push_str("// ---- Fulfillment condition types ----\n");
        code.push_str("// Mirrors FulfillmentMechanism oneof in dsm_app.proto.\n\n");
        code.push_str("sealed class FulfillmentCondition {\n");
        code.push_str("    /** proto tag 2 */\n");
        code.push_str("    data class Payment(\n");
        code.push_str("        val amount: BigInteger,\n");
        code.push_str("        val tokenId: String,\n");
        code.push_str("        val recipient: ByteArray,   // Base32 Crockford device_id\n");
        code.push_str(
            "        val verificationState: ByteArray  // BLAKE3-256 reference state hash\n",
        );
        code.push_str("    ) : FulfillmentCondition()\n\n");
        code.push_str("    /** proto tag 3 */\n");
        code.push_str("    data class CryptoCondition(\n");
        code.push_str("        val conditionHash: ByteArray,  // BLAKE3(\"DSM/crypto-condition\\0\" || preimage)\n");
        code.push_str("        val publicParams: ByteArray\n");
        code.push_str("    ) : FulfillmentCondition()\n\n");
        code.push_str("    /** proto tag 4 — k-of-n SPHINCS+ */\n");
        code.push_str("    data class MultiSignature(\n");
        code.push_str("        val publicKeys: List<ByteArray>,\n");
        code.push_str("        val threshold: Int\n");
        code.push_str("    ) : FulfillmentCondition()\n\n");
        code.push_str("    /** proto tag 5 */\n");
        code.push_str("    data class StateReference(\n");
        code.push_str("        val referenceStates: List<ByteArray>,\n");
        code.push_str("        val parameters: ByteArray\n");
        code.push_str("    ) : FulfillmentCondition()\n\n");
        code.push_str("    /** proto tag 6 */\n");
        code.push_str("    data class RandomWalkVerification(\n");
        code.push_str("        val verificationKey: ByteArray,\n");
        code.push_str("        val statement: String\n");
        code.push_str("    ) : FulfillmentCondition()\n\n");
        code.push_str("    /** proto tag 7 — all conditions required */\n");
        code.push_str("    data class And(val conditions: List<FulfillmentCondition>) : FulfillmentCondition()\n\n");
        code.push_str("    /** proto tag 8 — any condition satisfies */\n");
        code.push_str("    data class Or(val conditions: List<FulfillmentCondition>) : FulfillmentCondition()\n\n");
        code.push_str("    /** proto tag 9 — dual-hashlock Bitcoin HTLC (dBTC §6.2-6.4) */\n");
        code.push_str("    data class BitcoinHtlc(\n");
        code.push_str("        val hashLock: ByteArray,          // 32 bytes: SHA256(sk_V)\n");
        code.push_str("        val refundHashLock: ByteArray,    // 32 bytes: SHA256(rk_V)\n");
        code.push_str(
            "        val refundIterations: Long,        // DSM chain-tick count (not wall time)\n",
        );
        code.push_str(
            "        val bitcoinPubkey: ByteArray,      // 33 bytes: compressed pubkey\n",
        );
        code.push_str("        val expectedBtcAmountSats: Long,\n");
        code.push_str(
            "        val network: Int,                  // 0=mainnet 1=testnet 2=signet\n",
        );
        code.push_str("        val minConfirmations: Long         // canonical=100 (dBTC §6.4)\n");
        code.push_str("    ) : FulfillmentCondition()\n");
        code.push_str("}\n\n");

        // VaultLifecycle mirrors core VaultState
        code.push_str("enum class VaultLifecycle {\n");
        code.push_str("    LIMBO,     // vault created, condition not yet met\n");
        code.push_str("    ACTIVE,    // entry anchor buried (dBTC tap active)\n");
        code.push_str("    UNLOCKED,  // fulfillment proof accepted\n");
        code.push_str("    CLAIMED,   // assets transferred to claimant\n");
        code.push_str("    INVALIDATED\n");
        code.push_str("}\n\n");

        // VaultConfig
        code.push_str(&format!("data class {}VaultConfig(\n", class_name));
        code.push_str("    val vaultId: ByteArray,\n");
        code.push_str("    val fulfillmentCondition: FulfillmentCondition,\n");
        code.push_str("    val assets: List<AssetDefinition>\n");
        code.push_str(")\n\n");

        code.push_str("data class AssetDefinition(\n");
        code.push_str("    val assetId: String,\n");
        code.push_str("    val amount: BigInteger,\n");
        code.push_str(
            "    val chainStateHash: ByteArray?,   // BLAKE3-256 ref state (chain anchor)\n",
        );
        code.push_str("    val chainStateNumber: Long?,\n");
        code.push_str("    val metadata: Map<String, String>\n");
        code.push_str(")\n\n");

        Ok(code)
    }

    fn generate_policy_types(&self, _spec: &PolicySpecification) -> Result<String> {
        let mut code = String::new();

        // Policy configuration
        code.push_str("data class PolicyConfig(\n");
        code.push_str("    val policyId: ByteArray,\n");
        code.push_str("    val name: String,\n");
        code.push_str("    val version: String,\n");
        code.push_str("    val rules: List<TransferRule>,\n");
        code.push_str("    val metadata: Map<String, String>\n");
        code.push_str(")\n\n");

        // Transfer rule
        code.push_str("data class TransferRule(\n");
        code.push_str("    val name: String,\n");
        code.push_str("    val condition: RuleCondition,\n");
        code.push_str("    val action: RuleAction,\n");
        code.push_str("    val priority: Int\n");
        code.push_str(")\n\n");

        // Rule condition
        code.push_str("data class RuleCondition(\n");
        code.push_str("    val conditionType: ConditionType,\n");
        code.push_str("    val parameters: Map<String, String>\n");
        code.push_str(")\n\n");

        // Condition types enum
        code.push_str("enum class ConditionType {\n");
        code.push_str("    AMOUNT_LIMIT,\n");
        code.push_str("    ITERATION_WINDOW,\n");
        code.push_str("    WHITELIST,\n");
        code.push_str("    BLACKLIST,\n");
        code.push_str("    SIGNATURE_REQUIRED,\n");
        code.push_str("    CUSTOM\n");
        code.push_str("}\n\n");

        // Rule action enum
        code.push_str("enum class RuleAction {\n");
        code.push_str("    ALLOW,\n");
        code.push_str("    DENY,\n");
        code.push_str("    REQUIRE_APPROVAL\n");
        code.push_str("}\n\n");

        // Policy evaluation result
        code.push_str("data class PolicyEvaluationResult(\n");
        code.push_str("    val allowed: Boolean,\n");
        code.push_str("    val requiredApprovals: List<String>,\n");
        code.push_str("    val matchedRules: List<String>\n");
        code.push_str(")\n\n");

        Ok(code)
    }

    fn generate_vault_client_class(&self, spec: &VaultSpecification) -> Result<String> {
        let class_name = super::base_vault_name(spec);
        let mut code = String::new();

        code.push_str(&format!("class {}VaultClient(\n", class_name));
        code.push_str("    private val dsmSdk: DsmSdk,\n");
        code.push_str(&format!(
            "    private val config: {}VaultConfig\n",
            class_name
        ));
        code.push_str(") {\n\n");

        code.push_str("    fun createVault(): Result<ByteArray> {\n");
        code.push_str("        return dsmSdk.createVault(config)\n");
        code.push_str("    }\n\n");

        code.push_str("    fun unlockVault(conditionProof: ByteArray): Result<ByteArray> {\n");
        code.push_str("        // conditionProof must satisfy config.fulfillmentCondition.\n");
        code.push_str("        // The SDK verifies the proof against the on-chain commitment.\n");
        code.push_str("        return dsmSdk.unlockVault(config.vaultId, conditionProof)\n");
        code.push_str("    }\n\n");

        code.push_str("    fun checkLifecycle(): Result<VaultLifecycle> {\n");
        code.push_str("        return dsmSdk.getVaultLifecycle(config.vaultId)\n");
        code.push_str("    }\n\n");

        code.push_str("}\n\n");

        Ok(code)
    }

    fn generate_policy_client_class(&self, _spec: &PolicySpecification) -> Result<String> {
        let mut code = String::new();

        code.push_str("class PolicyClient(\n");
        code.push_str("    private val dsmSdk: DsmSdk,\n");
        code.push_str("    private val config: PolicyConfig\n");
        code.push_str(") {\n\n");

        code.push_str("    fun evaluateTransaction(\n");
        code.push_str("        transaction: ByteArray,\n");
        code.push_str("        context: TransactionContext\n");
        code.push_str("    ): Result<PolicyEvaluationResult> {\n");
        code.push_str("        // Evaluate all policy rules against the transaction\n");
        code.push_str("        val matchedRules = mutableListOf<String>()\n");
        code.push_str("        val requiredApprovals = mutableListOf<String>()\n");
        code.push_str("        var allowed = true\n\n");

        code.push_str("        // Sort rules by priority (highest first)\n");
        code.push_str(
            "        val sortedRules = config.rules.sortedByDescending { it.priority }\n\n",
        );

        code.push_str("        for (rule in sortedRules) {\n");
        code.push_str("            if (evaluateRule(rule, transaction, context)) {\n");
        code.push_str("                matchedRules.add(rule.name)\n");
        code.push_str("                when (rule.action) {\n");
        code.push_str("                    RuleAction.ALLOW -> {\n");
        code.push_str(
            "                        // Allow rule matched, continue checking other rules\n",
        );
        code.push_str("                    }\n");
        code.push_str("                    RuleAction.DENY -> {\n");
        code.push_str("                        allowed = false\n");
        code.push_str("                        break\n");
        code.push_str("                    }\n");
        code.push_str("                    RuleAction.REQUIRE_APPROVAL -> {\n");
        code.push_str("                        requiredApprovals.add(rule.name)\n");
        code.push_str("                    }\n");
        code.push_str("                }\n");
        code.push_str("            }\n");
        code.push_str("        }\n\n");

        code.push_str("        return Result.success(PolicyEvaluationResult(\n");
        code.push_str("            allowed = allowed,\n");
        code.push_str("            requiredApprovals = requiredApprovals,\n");
        code.push_str("            matchedRules = matchedRules\n");
        code.push_str("        ))\n");
        code.push_str("    }\n\n");

        code.push_str("    private fun evaluateRule(\n");
        code.push_str("        rule: TransferRule,\n");
        code.push_str("        transaction: ByteArray,\n");
        code.push_str("        context: TransactionContext\n");
        code.push_str("    ): Boolean {\n");
        code.push_str("        return when (rule.condition.conditionType) {\n");
        code.push_str("            ConditionType.AMOUNT_LIMIT -> {\n");
        code.push_str("                evaluateAmountLimit(rule.condition, context)\n");
        code.push_str("            }\n");
        code.push_str("            ConditionType.ITERATION_WINDOW -> {\n");
        code.push_str("                evaluateIterationWindow(rule.condition, context)\n");
        code.push_str("            }\n");
        code.push_str("            ConditionType.WHITELIST -> {\n");
        code.push_str("                evaluateWhitelist(rule.condition, context)\n");
        code.push_str("            }\n");
        code.push_str("            ConditionType.BLACKLIST -> {\n");
        code.push_str("                evaluateBlacklist(rule.condition, context)\n");
        code.push_str("            }\n");
        code.push_str("            ConditionType.SIGNATURE_REQUIRED -> {\n");
        code.push_str("                evaluateSignatureRequired(rule.condition, context)\n");
        code.push_str("            }\n");
        code.push_str("            ConditionType.CUSTOM -> {\n");
        code.push_str(
            "                evaluateCustomCondition(rule.condition, transaction, context)\n",
        );
        code.push_str("            }\n");
        code.push_str("        }\n");
        code.push_str("    }\n\n");

        code.push_str("    private fun evaluateAmountLimit(condition: RuleCondition, context: TransactionContext): Boolean {\n");
        code.push_str("        val maxAmount = condition.parameters[\"maxAmount\"]?.toBigIntegerOrNull() ?: return false\n");
        code.push_str("        return context.amount <= maxAmount\n");
        code.push_str("    }\n\n");

        // NOTE: DSM core/bridge are deterministic and must not depend on wall-clock time.
        // This generator previously emitted wall-clock-based checks, which
        // violates repo invariants. We therefore emit a fail-closed stub for ITERATION_WINDOW.
        // If iteration-window semantics are needed, they must be expressed in deterministic ticks
        // carried in the transaction/context (not wall-clock).
        code.push_str("    private fun evaluateIterationWindow(condition: RuleCondition, context: TransactionContext): Boolean {\n");
        code.push_str("        // Deterministic tick-based window check (no wall-clock).\n");
        code.push_str("        val maxIterations = condition.parameters[\"maxIterations\"]?.toLongOrNull() ?: return false\n");
        code.push_str("        return context.tick <= maxIterations\n");
        code.push_str("    }\n\n");

        code.push_str("    private fun evaluateWhitelist(condition: RuleCondition, context: TransactionContext): Boolean {\n");
        code.push_str("        val recipientList = condition.parameters[\"recipients\"] ?: return false\n");
        code.push_str("        val recipientStr = String(context.recipient)\n");
        code.push_str("        return recipientList.split(\",\").any { it.trim() == recipientStr }\n");
        code.push_str("    }\n\n");

        code.push_str("    private fun evaluateBlacklist(condition: RuleCondition, context: TransactionContext): Boolean {\n");
        code.push_str("        val recipientList = condition.parameters[\"recipients\"] ?: return true\n");
        code.push_str("        val recipientStr = String(context.recipient)\n");
        code.push_str("        return recipientList.split(\",\").none { it.trim() == recipientStr }\n");
        code.push_str("    }\n\n");

        code.push_str("    private fun evaluateSignatureRequired(condition: RuleCondition, context: TransactionContext): Boolean {\n");
        code.push_str("        val requiredSignatures = condition.parameters[\"count\"]?.toIntOrNull() ?: return false\n");
        code.push_str("        return context.signatureCount >= requiredSignatures\n");
        code.push_str("    }\n\n");

        code.push_str("    private fun evaluateCustomCondition(\n");
        code.push_str("        condition: RuleCondition,\n");
        code.push_str("        transaction: ByteArray,\n");
        code.push_str("        context: TransactionContext\n");
        code.push_str("    ): Boolean {\n");
        code.push_str(
            "        // Custom condition evaluation - extend this method for specific policies\n",
        );
        code.push_str("        return dsmSdk.evaluateCustomCondition(config.policyId, condition.parameters, transaction, context)\n");
        code.push_str("    }\n\n");

        code.push_str("    fun getPolicyRules(): List<TransferRule> {\n");
        code.push_str("        return config.rules\n");
        code.push_str("    }\n\n");

        code.push_str("    fun getPolicyInfo(): PolicyInfo {\n");
        code.push_str("        return PolicyInfo(\n");
        code.push_str("            name = config.name,\n");
        code.push_str("            version = config.version,\n");
        code.push_str("            ruleCount = config.rules.size,\n");
        code.push_str("            description = config.metadata[\"description\"]\n");
        code.push_str("        )\n");
        code.push_str("    }\n\n");

        code.push_str("}\n\n");

        // Transaction context
        code.push_str("data class TransactionContext(\n");
        code.push_str("    val sender: ByteArray,\n");
        code.push_str("    val recipient: ByteArray,\n");
        code.push_str("    val amount: BigInteger,\n");
        code.push_str("    val signatureCount: Int,\n");
        code.push_str("    val tick: Long,\n");
        code.push_str("    val metadata: Map<String, String>\n");
        code.push_str(")\n\n");

        // Policy info
        code.push_str("data class PolicyInfo(\n");
        code.push_str("    val name: String,\n");
        code.push_str("    val version: String,\n");
        code.push_str("    val ruleCount: Int,\n");
        code.push_str("    val description: String?\n");
        code.push_str(")\n\n");

        Ok(code)
    }

    fn generate_factory_class(&self, spec: &VaultSpecification) -> Result<String> {
        let class_name = super::base_vault_name(spec);
        let mut code = String::new();

        code.push_str(&format!("class {}VaultFactory(\n", class_name));
        code.push_str("    private val dsmSdk: DsmSdk\n");
        code.push_str(") {\n\n");

        code.push_str(&format!(
            "    fun createClient(config: {}VaultConfig): {}VaultClient {{\n",
            class_name, class_name
        ));
        code.push_str(&format!(
            "        return {}VaultClient(dsmSdk, config)\n",
            class_name
        ));
        code.push_str("    }\n\n");

        code.push_str("    // Callers must supply a valid vault_id from the DSM SDK\n");
        code.push_str("    // (sdk.generateVaultId() or from a prior DlvCreate operation).\n");
        code.push_str("}\n\n");

        Ok(code)
    }

    fn generate_test_vectors(&self) -> Result<String> {
        let mut code = String::new();

        code.push_str("// Test vectors for CI validation\n");
        code.push_str("object TestVectors {\n");
        code.push_str("    // Minimal multi-sig vault\n");
        code.push_str("    val multiSigCondition = FulfillmentCondition.MultiSignature(\n");
        code.push_str("        publicKeys = listOf(byteArrayOf(1, 2, 3)),\n");
        code.push_str("        threshold = 1\n");
        code.push_str("    )\n");
        code.push_str("}\n\n");

        Ok(code)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::*;

    #[test]
    fn test_kotlin_vault_generation() {
        let vault_spec = VaultSpecification {
            name: "TestVault".to_string(),
            version: "1.0.0".to_string(),
            description: Some("A test vault for unit testing".to_string()),
            fulfillment_condition: crate::schema::FulfillmentConditionSpec::MultiSignature(
                crate::schema::MultiSignatureSpec {
                    public_keys: vec!["KEY1AAAAAA".to_string(), "KEY2AAAAAA".to_string()],
                    threshold: 2,
                },
            ),
            assets: vec![AssetDefinition {
                asset_id: "DSM".to_string(),
                amount: 1000,
                chain_state_hash: None,
                chain_state_number: None,
                metadata: None,
            }],
            tick_lock: None,
            recovery: None,
            metadata: None,
        };

        let spec = DsmSpecification::Vault(vault_spec);
        let generator = KotlinGenerator::new(false, false);

        match generator.generate(&spec) {
            Ok(generated_code) => {
                assert!(generated_code.contains("auto-generated by dsm-gen"));
                assert!(generated_code.contains("TestVaultClient"));
                assert!(generated_code.contains("class TestVaultClient"));
                assert!(generated_code.contains("fun createVault"));
                assert!(generated_code.contains("fun unlockVault"));
                assert!(generated_code.contains("FulfillmentCondition"));
                assert!(generated_code.contains("sealed class FulfillmentCondition"));
                assert!(generated_code.contains("BitcoinHtlc"));
                assert!(generated_code.contains("MultiSignature"));
                assert!(generated_code.contains("RandomWalkVerification"));
                assert!(generated_code.contains("VaultLifecycle"));
                // Invariant checks
                assert!(!generated_code.contains("duration_seconds"));
                assert!(!generated_code.contains("TimeLock"));
                assert!(!generated_code.contains("time_lock"));
            }
            Err(e) => panic!("generate failed: {}", e),
        }
    }
}
