//! Rust code generator for DSM specifications
//!
//! Generates type-safe Rust clients for DSM vaults and policies
//! with compile-time safety and direct SDK integration.

use crate::generators::CodeGenerator;
use crate::schema::{DsmSpecification, PolicySpecification, VaultSpecification};
use anyhow::Result;

pub struct RustGenerator {
    include_factory: bool,
    include_test_vectors: bool,
}

impl RustGenerator {
    pub fn new(include_factory: bool, include_test_vectors: bool) -> Self {
        Self {
            include_factory,
            include_test_vectors,
        }
    }
}

impl CodeGenerator for RustGenerator {
    fn generate(&self, spec: &DsmSpecification) -> Result<String> {
        match spec {
            DsmSpecification::Vault(vault_spec) => self.generate_vault_client(vault_spec),
            DsmSpecification::Policy(policy_spec) => self.generate_policy_client(policy_spec),
        }
    }

    fn file_extension(&self) -> &'static str {
        "rs"
    }

    fn language_name(&self) -> &'static str {
        "Rust"
    }
}

impl RustGenerator {
    fn generate_header(&self) -> String {
        // Clockless/deterministic: never include wall-clock markers in generated output.
        let marker_suffix = String::new();

        format!(
            "// auto-generated by dsm-gen v{}{} — DO NOT EDIT\n\
             // This file was automatically generated from a DSM specification.\n\
             // For more information about DSM, visit: https://github.com/dsm-project\n\n",
            env!("CARGO_PKG_VERSION"),
            marker_suffix
        )
    }

    fn generate_imports(&self) -> String {
        "use dsm_sdk::{DsmSdk, Result};\nuse serde::{Deserialize, Serialize};\nuse std::collections::HashMap;\n\n".to_string()
    }

    fn generate_vault_client(&self, spec: &VaultSpecification) -> Result<String> {
        let mut code = String::new();

        // Header comment
        code.push_str(&self.generate_header());

        // Imports
        code.push_str(&self.generate_imports());

        // Type definitions
        code.push_str(&self.generate_vault_types(spec)?);

        // Client struct
        code.push_str(&self.generate_vault_client_struct(spec)?);

        // Implementation
        code.push_str(&self.generate_vault_client_impl(spec)?);

        // Factory struct (if requested)
        if self.include_factory {
            code.push_str(&self.generate_factory_struct(spec)?);
            code.push_str(&self.generate_factory_impl(spec)?);
        }

        // Test vectors (if requested)
        if self.include_test_vectors {
            code.push_str(&self.generate_test_vectors()?);
        }

        Ok(code)
    }

    fn generate_policy_client(&self, spec: &PolicySpecification) -> Result<String> {
        let mut code = String::new();

        // Header comment
        code.push_str(&self.generate_header());

        // Imports
        code.push_str(&self.generate_imports());

        // Type definitions
        code.push_str(&self.generate_policy_types(spec)?);

        // Client struct
        code.push_str(&self.generate_policy_client_struct(spec)?);

        // Implementation
        code.push_str(&self.generate_policy_client_impl(spec)?);

        Ok(code)
    }

    fn generate_vault_types(&self, spec: &VaultSpecification) -> Result<String> {
        let class_name = super::base_vault_name(spec);
        let mut code = String::new();

        // FulfillmentCondition mirrors FulfillmentMechanism oneof in dsm_app.proto.
        // Proto tag 1 (time_release) absent: DSM is clockless (Invariant #4).
        code.push_str("// tag 2-9 match FulfillmentMechanism oneof in dsm_app.proto\n");
        code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        code.push_str("pub struct PaymentCondition {\n");
        code.push_str("    pub amount: u64,\n");
        code.push_str("    pub token_id: String,\n");
        code.push_str("    pub recipient: Vec<u8>,       // Base32 Crockford at boundary\n");
        code.push_str("    pub verification_state: Vec<u8>, // BLAKE3-256 hash\n");
        code.push_str("}\n\n");

        code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        code.push_str("pub struct CryptoCondition {\n");
        code.push_str("    pub condition_hash: Vec<u8>,  // BLAKE3(\"DSM/crypto-condition\\0\" || preimage)\n");
        code.push_str("    pub public_params: Vec<u8>,\n");
        code.push_str("}\n\n");

        code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        code.push_str("pub struct MultiSignature {\n");
        code.push_str("    pub public_keys: Vec<Vec<u8>>, // SPHINCS+ public keys\n");
        code.push_str("    pub threshold: u32,\n");
        code.push_str("}\n\n");

        code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        code.push_str("pub struct StateReference {\n");
        code.push_str("    pub reference_states: Vec<Vec<u8>>, // BLAKE3-256 hashes\n");
        code.push_str("    pub parameters: Vec<u8>,\n");
        code.push_str("}\n\n");

        code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        code.push_str("pub struct RandomWalkVerification {\n");
        code.push_str("    pub verification_key: Vec<u8>,\n");
        code.push_str("    pub statement: String,\n");
        code.push_str("}\n\n");

        code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        code.push_str("pub struct BitcoinHtlc {\n");
        code.push_str("    pub hash_lock: Vec<u8>,           // 32 bytes: SHA256(sk_V)\n");
        code.push_str("    pub refund_hash_lock: Vec<u8>,    // 32 bytes: SHA256(rk_V)\n");
        code.push_str(
            "    pub refund_iterations: u64,       // DSM chain-tick count (not wall time)\n",
        );
        code.push_str("    pub bitcoin_pubkey: Vec<u8>,       // 33 bytes: compressed\n");
        code.push_str("    pub expected_btc_amount_sats: u64,\n");
        code.push_str("    pub network: u32,                 // 0=mainnet 1=testnet 2=signet\n");
        code.push_str("    pub min_confirmations: u64,        // canonical=100 (dBTC §6.4)\n");
        code.push_str("}\n\n");

        code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        code.push_str("#[serde(tag = \"type\", rename_all = \"snake_case\")]\n");
        code.push_str("pub enum FulfillmentCondition {\n");
        code.push_str("    Payment(PaymentCondition),               // proto tag 2\n");
        code.push_str("    CryptoCondition(CryptoCondition),        // proto tag 3\n");
        code.push_str("    MultiSignature(MultiSignature),           // proto tag 4\n");
        code.push_str("    StateReference(StateReference),          // proto tag 5\n");
        code.push_str("    RandomWalkVerification(RandomWalkVerification), // proto tag 6\n");
        code.push_str("    And(Vec<Box<FulfillmentCondition>>),     // proto tag 7\n");
        code.push_str("    Or(Vec<Box<FulfillmentCondition>>),      // proto tag 8\n");
        code.push_str("    BitcoinHtlc(BitcoinHtlc),               // proto tag 9\n");
        code.push_str("}\n\n");

        // VaultLifecycle mirrors core VaultState
        code.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]\n");
        code.push_str("pub enum VaultLifecycle {\n");
        code.push_str("    Limbo,       // vault created, condition not yet met\n");
        code.push_str("    Active,      // entry anchor buried (dBTC tap active)\n");
        code.push_str("    Unlocked,    // fulfillment proof accepted\n");
        code.push_str("    Claimed,     // assets transferred to claimant\n");
        code.push_str("    Invalidated,\n");
        code.push_str("}\n\n");

        code.push_str(&format!(
            "#[derive(Debug, Clone, Serialize, Deserialize)]\npub struct {}VaultConfig {{\n",
            class_name
        ));
        code.push_str("    pub vault_id: Vec<u8>,\n");
        code.push_str("    pub fulfillment_condition: FulfillmentCondition,\n");
        code.push_str("    pub assets: Vec<AssetDefinition>,\n");
        code.push_str("}\n\n");

        code.push_str(
            "#[derive(Debug, Clone, Serialize, Deserialize)]\npub struct AssetDefinition {\n",
        );
        code.push_str("    pub asset_id: String,\n");
        code.push_str("    pub amount: u64,\n");
        code.push_str("    pub chain_state_hash: Option<Vec<u8>>,   // BLAKE3-256 ref state\n");
        code.push_str("    pub chain_state_number: Option<u64>,\n");
        code.push_str("    pub metadata: HashMap<String, String>,\n");
        code.push_str("}\n\n");

        Ok(code)
    }

    fn generate_policy_types(&self, _spec: &PolicySpecification) -> Result<String> {
        let mut code = String::new();

        // Policy configuration
        code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        code.push_str("pub struct PolicyConfig {\n");
        code.push_str("    pub policy_id: Vec<u8>,\n");
        code.push_str("    pub name: String,\n");
        code.push_str("    pub version: String,\n");
        code.push_str("    pub rules: Vec<TransferRule>,\n");
        code.push_str("    pub metadata: HashMap<String, String>,\n");
        code.push_str("}\n\n");

        // Transfer rule
        code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        code.push_str("pub struct TransferRule {\n");
        code.push_str("    pub name: String,\n");
        code.push_str("    pub condition: RuleCondition,\n");
        code.push_str("    pub action: RuleAction,\n");
        code.push_str("    pub priority: u32,\n");
        code.push_str("}\n\n");

        // Rule condition
        code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        code.push_str("pub struct RuleCondition {\n");
        code.push_str("    pub condition_type: ConditionType,\n");
        code.push_str("    pub parameters: HashMap<String, String>,\n");
        code.push_str("}\n\n");

        // Condition types enum
        code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        code.push_str("pub enum ConditionType {\n");
        code.push_str("    #[serde(rename = \"amount_limit\")]\n");
        code.push_str("    AmountLimit,\n");
        code.push_str("    #[serde(rename = \"iteration_window\")]\n");
        code.push_str("    IterationWindow,\n");
        code.push_str("    #[serde(rename = \"whitelist\")]\n");
        code.push_str("    Whitelist,\n");
        code.push_str("    #[serde(rename = \"blacklist\")]\n");
        code.push_str("    Blacklist,\n");
        code.push_str("    #[serde(rename = \"signature_required\")]\n");
        code.push_str("    SignatureRequired,\n");
        code.push_str("    #[serde(rename = \"custom\")]\n");
        code.push_str("    Custom,\n");
        code.push_str("}\n\n");

        // Rule action enum
        code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        code.push_str("#[serde(tag = \"type\")]\n");
        code.push_str("pub enum RuleAction {\n");
        code.push_str("    #[serde(rename = \"allow\")]\n");
        code.push_str("    Allow,\n");
        code.push_str("    #[serde(rename = \"deny\")]\n");
        code.push_str("    Deny,\n");
        code.push_str("    #[serde(rename = \"require_approval\")]\n");
        code.push_str("    RequireApproval,\n");
        code.push_str("}\n\n");

        // Policy evaluation result
        code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        code.push_str("pub struct PolicyEvaluationResult {\n");
        code.push_str("    pub allowed: bool,\n");
        code.push_str("    pub required_approvals: Vec<String>,\n");
        code.push_str("    pub matched_rules: Vec<String>,\n");
        code.push_str("}\n\n");

        Ok(code)
    }

    fn generate_vault_client_struct(&self, spec: &VaultSpecification) -> Result<String> {
        let class_name = super::base_vault_name(spec);
        let mut code = String::new();

        code.push_str(&format!(
            "pub struct {}VaultClient<S: DsmSdk> {{\n",
            class_name
        ));
        code.push_str("    sdk: S,\n");
        code.push_str(&format!("    config: {}VaultConfig,\n", class_name));
        code.push_str("}\n\n");

        Ok(code)
    }

    fn generate_vault_client_impl(&self, spec: &VaultSpecification) -> Result<String> {
        let class_name = super::base_vault_name(spec);
        let mut code = String::new();

        code.push_str(&format!(
            "impl<S: DsmSdk> {}VaultClient<S> {{\n",
            class_name
        ));
        code.push_str(&format!(
            "    pub fn new(sdk: S, config: {}VaultConfig) -> Self {{\n",
            class_name
        ));
        code.push_str("        Self { sdk, config }\n");
        code.push_str("    }\n\n");

        code.push_str("    pub fn create_vault(&self) -> Result<Vec<u8>> {\n");
        code.push_str("        self.sdk.create_vault(&self.config)\n");
        code.push_str("    }\n\n");

        code.push_str(
            "    pub fn unlock_vault(&self, condition_proof: &[u8]) -> Result<Vec<u8>> {\n",
        );
        code.push_str("        // condition_proof must satisfy config.fulfillment_condition.\n");
        code.push_str("        // The SDK verifies the proof against the on-chain commitment.\n");
        code.push_str("        self.sdk.unlock_vault(&self.config.vault_id, condition_proof)\n");
        code.push_str("    }\n\n");

        code.push_str("    pub fn check_lifecycle(&self) -> Result<VaultLifecycle> {\n");
        code.push_str("        self.sdk.get_vault_lifecycle(&self.config.vault_id)\n");
        code.push_str("    }\n\n");

        code.push_str("}\n\n");

        Ok(code)
    }

    fn generate_policy_client_struct(&self, _spec: &PolicySpecification) -> Result<String> {
        let mut code = String::new();

        code.push_str("pub struct PolicyClient<S: DsmSdk> {\n");
        code.push_str("    sdk: S,\n");
        code.push_str("    config: PolicyConfig,\n");
        code.push_str("}\n\n");

        Ok(code)
    }

    fn generate_policy_client_impl(&self, _spec: &PolicySpecification) -> Result<String> {
        let mut code = String::new();

        code.push_str("impl<S: DsmSdk> PolicyClient<S> {\n");
        code.push_str("    pub fn new(sdk: S, config: PolicyConfig) -> Self {\n");
        code.push_str("        Self { sdk, config }\n");
        code.push_str("    }\n\n");

        code.push_str("    pub fn evaluate_transaction(\n");
        code.push_str("        &self,\n");
        code.push_str("        transaction: &[u8],\n");
        code.push_str("        context: &TransactionContext,\n");
        code.push_str("    ) -> Result<PolicyEvaluationResult> {\n");
        code.push_str("        // Evaluate all policy rules against the transaction\n");
        code.push_str("        let mut matched_rules = Vec::new();\n");
        code.push_str("        let mut required_approvals = Vec::new();\n");
        code.push_str("        let mut allowed = true;\n\n");

        code.push_str("        // Sort rules by priority (highest first)\n");
        code.push_str("        let mut sorted_rules = self.config.rules.clone();\n");
        code.push_str("        sorted_rules.sort_by(|a, b| b.priority.cmp(&a.priority));\n\n");

        code.push_str("        for rule in &sorted_rules {\n");
        code.push_str("            if self.evaluate_rule(rule, transaction, context)? {\n");
        code.push_str("                matched_rules.push(rule.name.clone());\n");
        code.push_str("                match &rule.action {\n");
        code.push_str("                    RuleAction::Allow => {\n");
        code.push_str(
            "                        // Allow rule matched, continue checking other rules\n",
        );
        code.push_str("                    }\n");
        code.push_str("                    RuleAction::Deny => {\n");
        code.push_str("                        allowed = false;\n");
        code.push_str("                        break;\n");
        code.push_str("                    }\n");
        code.push_str("                    RuleAction::RequireApproval => {\n");
        code.push_str("                        required_approvals.push(rule.name.clone());\n");
        code.push_str("                    }\n");
        code.push_str("                }\n");
        code.push_str("            }\n");
        code.push_str("        }\n\n");

        code.push_str("        Ok(PolicyEvaluationResult {\n");
        code.push_str("            allowed,\n");
        code.push_str("            required_approvals,\n");
        code.push_str("            matched_rules,\n");
        code.push_str("        })\n");
        code.push_str("    }\n\n");

        code.push_str("    fn evaluate_rule(\n");
        code.push_str("        &self,\n");
        code.push_str("        rule: &TransferRule,\n");
        code.push_str("        transaction: &[u8],\n");
        code.push_str("        context: &TransactionContext,\n");
        code.push_str("    ) -> Result<bool> {\n");
        code.push_str("        match &rule.condition.condition_type {\n");
        code.push_str("            ConditionType::AmountLimit => {\n");
        code.push_str("                self.evaluate_amount_limit(&rule.condition, context)\n");
        code.push_str("            }\n");
        code.push_str("            ConditionType::IterationWindow => {\n");
        code.push_str("                self.evaluate_iteration_window(&rule.condition, context)\n");
        code.push_str("            }\n");
        code.push_str("            ConditionType::Whitelist => {\n");
        code.push_str("                self.evaluate_whitelist(&rule.condition, context)\n");
        code.push_str("            }\n");
        code.push_str("            ConditionType::Blacklist => {\n");
        code.push_str("                self.evaluate_blacklist(&rule.condition, context)\n");
        code.push_str("            }\n");
        code.push_str("            ConditionType::SignatureRequired => {\n");
        code.push_str(
            "                self.evaluate_signature_required(&rule.condition, context)\n",
        );
        code.push_str("            }\n");
        code.push_str("            ConditionType::Custom => {\n");
        code.push_str("                self.evaluate_custom_condition(&rule.condition, transaction, context)\n");
        code.push_str("            }\n");
        code.push_str("        }\n");
        code.push_str("    }\n\n");

        code.push_str("    fn evaluate_amount_limit(\n");
        code.push_str("        &self,\n");
        code.push_str("        condition: &RuleCondition,\n");
        code.push_str("        context: &TransactionContext,\n");
        code.push_str("    ) -> Result<bool> {\n");
        code.push_str("        if let Some(max_str) = condition.parameters.get(\"maxAmount\") {\n");
        code.push_str("            if let Ok(max_val) = max_str.parse::<u64>() {\n");
        code.push_str("                return Ok(context.amount <= max_val);\n");
        code.push_str("            }\n");
        code.push_str("        }\n");
        code.push_str("        Ok(false)\n");
        code.push_str("    }\n\n");

        // NOTE: DSM core/bridge are deterministic and must not depend on wall-clock time.
        // This generator previously emitted wall-clock-based checks, which violates
        // repo invariants. We therefore emit a fail-closed stub for ITERATION_WINDOW.
        // If iteration-window semantics are needed, they must be expressed in deterministic ticks
        // carried in the transaction/context (not wall-clock).
        code.push_str("    fn evaluate_iteration_window(\n");
        code.push_str("        &self,\n");
        code.push_str("        condition: &RuleCondition,\n");
        code.push_str("        context: &TransactionContext,\n");
        code.push_str("    ) -> Result<bool> {\n");
        code.push_str("        // Deterministic tick-based window check (no wall-clock).\n");
        code.push_str("        if let Some(max_str) = condition.parameters.get(\"maxIterations\") {\n");
        code.push_str("            if let Ok(max_tick) = max_str.parse::<u64>() {\n");
        code.push_str("                return Ok(context.tick <= max_tick);\n");
        code.push_str("            }\n");
        code.push_str("        }\n");
        code.push_str("        Ok(false)\n");
        code.push_str("    }\n\n");

        code.push_str("    fn evaluate_whitelist(\n");
        code.push_str("        &self,\n");
        code.push_str("        condition: &RuleCondition,\n");
        code.push_str("        context: &TransactionContext,\n");
        code.push_str("    ) -> Result<bool> {\n");
        // recipients is a comma-separated list in the String parameter
        code.push_str("        if let Some(list) = condition.parameters.get(\"recipients\") {\n");
        code.push_str(
            "            let recipient_str = String::from_utf8_lossy(&context.recipient);\n",
        );
        code.push_str(
            "            return Ok(list.split(',').any(|r| r.trim() == recipient_str.as_ref()));\n",
        );
        code.push_str("        }\n");
        code.push_str("        Ok(false)\n");
        code.push_str("    }\n\n");

        code.push_str("    fn evaluate_blacklist(\n");
        code.push_str("        &self,\n");
        code.push_str("        condition: &RuleCondition,\n");
        code.push_str("        context: &TransactionContext,\n");
        code.push_str("    ) -> Result<bool> {\n");
        code.push_str("        if let Some(list) = condition.parameters.get(\"recipients\") {\n");
        code.push_str(
            "            let recipient_str = String::from_utf8_lossy(&context.recipient);\n",
        );
        code.push_str(
            "            if list.split(',').any(|r| r.trim() == recipient_str.as_ref()) {\n",
        );
        code.push_str("                return Ok(false);\n");
        code.push_str("            }\n");
        code.push_str("        }\n");
        code.push_str("        Ok(true)\n");
        code.push_str("    }\n\n");

        code.push_str("    fn evaluate_signature_required(\n");
        code.push_str("        &self,\n");
        code.push_str("        condition: &RuleCondition,\n");
        code.push_str("        context: &TransactionContext,\n");
        code.push_str("    ) -> Result<bool> {\n");
        code.push_str("        if let Some(count_str) = condition.parameters.get(\"count\") {\n");
        code.push_str("            if let Ok(required) = count_str.parse::<usize>() {\n");
        code.push_str("                return Ok(context.signature_count >= required);\n");
        code.push_str("            }\n");
        code.push_str("        }\n");
        code.push_str("        Ok(false)\n");
        code.push_str("    }\n\n");

        code.push_str("    fn evaluate_custom_condition(\n");
        code.push_str("        &self,\n");
        code.push_str("        condition: &RuleCondition,\n");
        code.push_str("        transaction: &[u8],\n");
        code.push_str("        context: &TransactionContext,\n");
        code.push_str("    ) -> Result<bool> {\n");
        code.push_str(
            "        // Custom condition evaluation - extend this method for specific policies\n",
        );
        code.push_str("        self.sdk.evaluate_custom_condition(\n");
        code.push_str("            &self.config.policy_id,\n");
        code.push_str("            &condition.parameters,\n");
        code.push_str("            transaction,\n");
        code.push_str("            context,\n");
        code.push_str("        )\n");
        code.push_str("    }\n\n");

        code.push_str("    pub fn get_policy_rules(&self) -> &[TransferRule] {\n");
        code.push_str("        &self.config.rules\n");
        code.push_str("    }\n\n");

        code.push_str("    pub fn get_policy_info(&self) -> PolicyInfo {\n");
        code.push_str("        PolicyInfo {\n");
        code.push_str("            name: self.config.name.clone(),\n");
        code.push_str("            version: self.config.version.clone(),\n");
        code.push_str("            rule_count: self.config.rules.len(),\n");
        code.push_str(
            "            description: self.config.metadata.get(\"description\").cloned(),\n",
        );
        code.push_str("        }\n");
        code.push_str("    }\n\n");

        code.push_str("}\n\n");

        // Transaction context
        code.push_str("#[derive(Debug, Clone)]\n");
        code.push_str("pub struct TransactionContext {\n");
        code.push_str("    pub sender: Vec<u8>,\n");
        code.push_str("    pub recipient: Vec<u8>,\n");
        code.push_str("    pub amount: u64,\n");
        code.push_str("    pub signature_count: usize,\n");
        code.push_str("    pub tick: u64,\n");
        code.push_str("    pub metadata: HashMap<String, String>,\n");
        code.push_str("}\n\n");

        // Policy info
        code.push_str("#[derive(Debug, Clone)]\n");
        code.push_str("pub struct PolicyInfo {\n");
        code.push_str("    pub name: String,\n");
        code.push_str("    pub version: String,\n");
        code.push_str("    pub rule_count: usize,\n");
        code.push_str("    pub description: Option<String>,\n");
        code.push_str("}\n\n");

        Ok(code)
    }

    fn generate_factory_struct(&self, spec: &VaultSpecification) -> Result<String> {
        let class_name = super::base_vault_name(spec);
        let mut code = String::new();

        code.push_str(&format!(
            "pub struct {}VaultFactory<S: DsmSdk> {{\n",
            class_name
        ));
        code.push_str("    sdk: S,\n");
        code.push_str("}\n\n");

        Ok(code)
    }

    fn generate_factory_impl(&self, spec: &VaultSpecification) -> Result<String> {
        let class_name = super::base_vault_name(spec);
        let mut code = String::new();

        code.push_str(&format!(
            "impl<S: DsmSdk + Clone> {}VaultFactory<S> {{\n",
            class_name
        ));
        code.push_str("    pub fn new(sdk: S) -> Self {\n");
        code.push_str("        Self { sdk }\n");
        code.push_str("    }\n\n");

        code.push_str(&format!(
            "    pub fn create_client(&self, config: {}VaultConfig) -> {}VaultClient<S> {{\n",
            class_name, class_name
        ));
        code.push_str(&format!(
            "        {}VaultClient::new(self.sdk.clone(), config)\n",
            class_name
        ));
        code.push_str("    }\n\n");

        code.push_str(
            "    // Callers must supply a valid vault_id obtained from sdk.generate_vault_id()\n",
        );
        code.push_str(
            "    // or from a prior DlvCreate operation. The SDK is the authoritative source.\n",
        );
        code.push_str("}\n\n");

        Ok(code)
    }

    fn generate_test_vectors(&self) -> Result<String> {
        let mut code = String::new();

        code.push_str("#[cfg(test)]\nmod test_vectors {\n");
        code.push_str("    use super::*;\n\n");
        code.push_str("    pub fn minimal_multi_sig() -> FulfillmentCondition {\n");
        code.push_str("        FulfillmentCondition::MultiSignature(MultiSignature {\n");
        code.push_str("            public_keys: vec![vec![1, 2, 3]],\n");
        code.push_str("            threshold: 1,\n");
        code.push_str("        })\n");
        code.push_str("    }\n");
        code.push_str("}\n\n");

        Ok(code)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::*;

    #[test]
    fn test_rust_vault_generation() {
        let vault_spec = VaultSpecification {
            name: "TestVault".to_string(),
            version: "1.0.0".to_string(),
            description: Some("A test vault for unit testing".to_string()),
            fulfillment_condition: FulfillmentConditionSpec::MultiSignature(MultiSignatureSpec {
                public_keys: vec!["KEY1AAAAAA".to_string(), "KEY2AAAAAA".to_string()],
                threshold: 2,
            }),
            assets: vec![AssetDefinition {
                asset_id: "DSM".to_string(),
                amount: 1000,
                chain_state_hash: None,
                chain_state_number: None,
                metadata: None,
            }],
            tick_lock: None,
            recovery: None,
            metadata: None,
        };

        let spec = DsmSpecification::Vault(vault_spec);
        let generator = RustGenerator::new(false, false);

        match generator.generate(&spec) {
            Ok(generated_code) => {
                assert!(generated_code.contains("auto-generated by dsm-gen"));
                assert!(generated_code.contains("TestVaultClient"));
                assert!(generated_code.contains("struct TestVaultClient"));
                assert!(generated_code.contains("pub fn create_vault"));
                assert!(generated_code.contains("pub fn unlock_vault"));
                assert!(generated_code.contains("enum FulfillmentCondition"));
                assert!(generated_code.contains("BitcoinHtlc"));
                assert!(generated_code.contains("MultiSignature"));
                assert!(generated_code.contains("RandomWalkVerification"));
                assert!(generated_code.contains("VaultLifecycle"));
                // Invariants
                assert!(!generated_code.contains("duration_seconds"));
                assert!(!generated_code.contains("TimeLock"));
                assert!(!generated_code.contains("serde_json"));
                assert!(!generated_code.contains("lock_conditions"));
            }
            Err(e) => panic!("generate failed: {}", e),
        }
    }
}
