//! Swift code generator for DSM specifications
//!
//! Generates type-safe Swift clients for DSM vaults and policies
//! with compile-time safety and iOS integration.

use crate::generators::CodeGenerator;
use crate::schema::{DsmSpecification, PolicySpecification, VaultSpecification};
use anyhow::Result;

pub struct SwiftGenerator {
    include_factory: bool,
    include_test_vectors: bool,
}

impl SwiftGenerator {
    pub fn new(include_factory: bool, include_test_vectors: bool) -> Self {
        Self {
            include_factory,
            include_test_vectors,
        }
    }
}

impl CodeGenerator for SwiftGenerator {
    fn generate(&self, spec: &DsmSpecification) -> Result<String> {
        match spec {
            DsmSpecification::Vault(vault_spec) => self.generate_vault_client(vault_spec),
            DsmSpecification::Policy(policy_spec) => self.generate_policy_client(policy_spec),
        }
    }

    fn file_extension(&self) -> &'static str {
        "swift"
    }

    fn language_name(&self) -> &'static str {
        "Swift"
    }
}

impl SwiftGenerator {
    fn generate_header(&self) -> String {
        // Clockless/deterministic: never include wall-clock markers in generated output.
        let marker_suffix = String::new();

        format!(
            "// auto-generated by dsm-gen v{}{} — DO NOT EDIT\n\
             // This file was automatically generated from a DSM specification.\n\
             // For more information about DSM, visit: https://github.com/dsm-project\n\n",
            env!("CARGO_PKG_VERSION"),
            marker_suffix
        )
    }

    fn generate_imports(&self) -> String {
        "import Foundation\n\n".to_string()
    }

    fn generate_vault_client(&self, spec: &VaultSpecification) -> Result<String> {
        let mut code = String::new();

        // Header comment
        code.push_str(&self.generate_header());

        // Imports
        code.push_str(&self.generate_imports());

        // Type definitions
        code.push_str(&self.generate_vault_types(spec)?);

        // Client class
        code.push_str(&self.generate_vault_client_class(spec)?);

        // Factory class (if requested)
        if self.include_factory {
            code.push_str(&self.generate_factory_class(spec)?);
        }

        // Test vectors (if requested)
        if self.include_test_vectors {
            code.push_str(&self.generate_test_vectors()?);
        }

        Ok(code)
    }

    fn generate_policy_client(&self, spec: &PolicySpecification) -> Result<String> {
        let mut code = String::new();

        // Header comment
        code.push_str(&self.generate_header());

        // Imports
        code.push_str(&self.generate_imports());

        // Type definitions
        code.push_str(&self.generate_policy_types(spec)?);

        // Client class
        code.push_str(&self.generate_policy_client_class(spec)?);

        Ok(code)
    }

    fn generate_vault_types(&self, spec: &VaultSpecification) -> Result<String> {
        let class_name = super::base_vault_name(spec);
        let mut code = String::new();

        // FulfillmentCondition indirect enum — mirrors FulfillmentMechanism oneof in dsm_app.proto.
        // Proto tag 1 (time_release) is absent: DSM is clockless (Invariant #4).
        code.push_str("// ---- Fulfillment condition types ----\n");
        code.push_str("// Mirrors FulfillmentMechanism oneof in dsm_app.proto.\n");
        code.push_str("// `indirect` enables recursive And/Or nesting.\n\n");

        code.push_str("struct PaymentCondition {\n");
        code.push_str("    let amount: UInt64\n");
        code.push_str("    let tokenId: String\n");
        code.push_str("    let recipient: Data    // Base32 Crockford device_id\n");
        code.push_str("    let verificationState: Data // BLAKE3-256 reference state hash\n");
        code.push_str("}\n\n");

        code.push_str("struct CryptoConditionParams {\n");
        code.push_str(
            "    let conditionHash: Data  // BLAKE3(\"DSM/crypto-condition\\0\" || preimage)\n",
        );
        code.push_str("    let publicParams: Data\n");
        code.push_str("}\n\n");

        code.push_str("struct MultiSignatureParams {\n");
        code.push_str("    let publicKeys: [Data]   // SPHINCS+ public keys\n");
        code.push_str("    let threshold: Int\n");
        code.push_str("}\n\n");

        code.push_str("struct StateReferenceParams {\n");
        code.push_str("    let referenceStates: [Data] // BLAKE3-256 hashes\n");
        code.push_str("    let parameters: Data\n");
        code.push_str("}\n\n");

        code.push_str("struct RandomWalkParams {\n");
        code.push_str("    let verificationKey: Data\n");
        code.push_str("    let statement: String\n");
        code.push_str("}\n\n");

        code.push_str("struct BitcoinHtlcParams {\n");
        code.push_str("    let hashLock: Data          // 32 bytes: SHA256(sk_V)\n");
        code.push_str("    let refundHashLock: Data    // 32 bytes: SHA256(rk_V)\n");
        code.push_str("    let refundIterations: UInt64 // DSM chain-tick count (not wall time)\n");
        code.push_str("    let bitcoinPubkey: Data     // 33 bytes: compressed pubkey\n");
        code.push_str("    let expectedBtcAmountSats: UInt64\n");
        code.push_str("    let network: UInt32         // 0=mainnet 1=testnet 2=signet\n");
        code.push_str("    let minConfirmations: UInt64 // canonical=100 (dBTC §6.4)\n");
        code.push_str("}\n\n");

        code.push_str("indirect enum FulfillmentCondition {\n");
        code.push_str("    case payment(PaymentCondition)               // proto tag 2\n");
        code.push_str("    case cryptoCondition(CryptoConditionParams)  // proto tag 3\n");
        code.push_str("    case multiSignature(MultiSignatureParams)    // proto tag 4\n");
        code.push_str("    case stateReference(StateReferenceParams)    // proto tag 5\n");
        code.push_str("    case randomWalkVerification(RandomWalkParams) // proto tag 6\n");
        code.push_str("    case and([FulfillmentCondition])             // proto tag 7\n");
        code.push_str("    case or([FulfillmentCondition])              // proto tag 8\n");
        code.push_str("    case bitcoinHtlc(BitcoinHtlcParams)          // proto tag 9\n");
        code.push_str("}\n\n");

        // VaultLifecycle mirrors core VaultState
        code.push_str("enum VaultLifecycle {\n");
        code.push_str("    case limbo       // vault created, condition not yet met\n");
        code.push_str("    case active      // entry anchor buried (dBTC tap active)\n");
        code.push_str("    case unlocked    // fulfillment proof accepted\n");
        code.push_str("    case claimed     // assets transferred to claimant\n");
        code.push_str("    case invalidated\n");
        code.push_str("}\n\n");

        // VaultConfig
        code.push_str(&format!("struct {}VaultConfig {{\n", class_name));
        code.push_str("    let vaultId: Data\n");
        code.push_str("    let fulfillmentCondition: FulfillmentCondition\n");
        code.push_str("    let assets: [AssetDefinition]\n");
        code.push_str("}\n\n");

        code.push_str("struct AssetDefinition {\n");
        code.push_str("    let assetId: String\n");
        code.push_str("    let amount: UInt64\n");
        code.push_str("    let chainStateHash: Data?    // BLAKE3-256 ref state (chain anchor)\n");
        code.push_str("    let chainStateNumber: UInt64?\n");
        code.push_str("    let metadata: [String: String]\n");
        code.push_str("}\n\n");

        Ok(code)
    }

    fn generate_policy_types(&self, _spec: &PolicySpecification) -> Result<String> {
        let mut code = String::new();

        // Policy configuration
        code.push_str("struct PolicyConfig {\n");
        code.push_str("    let policyId: Data\n");
        code.push_str("    let name: String\n");
        code.push_str("    let version: String\n");
        code.push_str("    let rules: [TransferRule]\n");
        code.push_str("    let metadata: [String: String]\n");
        code.push_str("}\n\n");

        // Transfer rule
        code.push_str("struct TransferRule {\n");
        code.push_str("    let name: String\n");
        code.push_str("    let condition: RuleCondition\n");
        code.push_str("    let action: RuleAction\n");
        code.push_str("    let priority: Int\n");
        code.push_str("}\n\n");

        // Rule condition
        code.push_str("struct RuleCondition {\n");
        code.push_str("    let conditionType: ConditionType\n");
        code.push_str("    let parameters: [String: String]\n");
        code.push_str("}\n\n");

        // Condition types enum
        code.push_str("enum ConditionType {\n");
        code.push_str("    case amountLimit\n");
        code.push_str("    case iterationWindow\n");
        code.push_str("    case whitelist\n");
        code.push_str("    case blacklist\n");
        code.push_str("    case signatureRequired\n");
        code.push_str("    case custom\n");
        code.push_str("}\n\n");

        // Rule action enum
        code.push_str("enum RuleAction {\n");
        code.push_str("    case allow\n");
        code.push_str("    case deny\n");
        code.push_str("    case requireApproval\n");
        code.push_str("}\n\n");

        // Policy evaluation result
        code.push_str("struct PolicyEvaluationResult {\n");
        code.push_str("    let allowed: Bool\n");
        code.push_str("    let requiredApprovals: [String]\n");
        code.push_str("    let matchedRules: [String]\n");
        code.push_str("}\n\n");

        Ok(code)
    }

    fn generate_vault_client_class(&self, spec: &VaultSpecification) -> Result<String> {
        let class_name = super::base_vault_name(spec);
        let mut code = String::new();

        code.push_str(&format!("class {}VaultClient {{\n", class_name));
        code.push_str("    private let dsmSdk: DsmSdk\n");
        code.push_str(&format!(
            "    private let config: {}VaultConfig\n\n",
            class_name
        ));

        code.push_str(&format!(
            "    init(dsmSdk: DsmSdk, config: {}VaultConfig) {{\n",
            class_name
        ));
        code.push_str("        self.dsmSdk = dsmSdk\n");
        code.push_str("        self.config = config\n");
        code.push_str("    }\n\n");

        code.push_str("    func createVault() throws -> Data {\n");
        code.push_str("        return try dsmSdk.createVault(config: config)\n");
        code.push_str("    }\n\n");

        code.push_str("    func unlockVault(conditionProof: Data) throws -> Data {\n");
        code.push_str("        // conditionProof must satisfy config.fulfillmentCondition.\n");
        code.push_str("        // The SDK verifies the proof against the on-chain commitment.\n");
        code.push_str("        return try dsmSdk.unlockVault(vaultId: config.vaultId, proof: conditionProof)\n");
        code.push_str("    }\n\n");

        code.push_str("    func checkLifecycle() throws -> VaultLifecycle {\n");
        code.push_str("        return try dsmSdk.getVaultLifecycle(vaultId: config.vaultId)\n");
        code.push_str("    }\n\n");

        code.push_str("}\n\n");

        Ok(code)
    }

    fn generate_policy_client_class(&self, _spec: &PolicySpecification) -> Result<String> {
        let mut code = String::new();

        code.push_str("class PolicyClient {\n");
        code.push_str("    private let dsmSdk: DsmSdk\n");
        code.push_str("    private let config: PolicyConfig\n\n");

        code.push_str("    init(dsmSdk: DsmSdk, config: PolicyConfig) {\n");
        code.push_str("        self.dsmSdk = dsmSdk\n");
        code.push_str("        self.config = config\n");
        code.push_str("    }\n\n");

        code.push_str("    func evaluateTransaction(transaction: Data, context: TransactionContext) throws -> PolicyEvaluationResult {\n");
        code.push_str("        // Evaluate all policy rules against the transaction\n");
        code.push_str("        var matchedRules: [String] = []\n");
        code.push_str("        var requiredApprovals: [String] = []\n");
        code.push_str("        var allowed = true\n\n");

        code.push_str("        // Sort rules by priority (highest first)\n");
        code.push_str(
            "        let sortedRules = config.rules.sorted { $0.priority > $1.priority }\n\n",
        );

        code.push_str("        for rule in sortedRules {\n");
        code.push_str(
            "            if evaluateRule(rule, transaction: transaction, context: context) {\n",
        );
        code.push_str("                matchedRules.append(rule.name)\n");
        code.push_str("                switch rule.action {\n");
        code.push_str("                case .allow:\n");
        code.push_str("                    // Allow rule matched, continue checking other rules\n");
        code.push_str("                    break\n");
        code.push_str("                case .deny:\n");
        code.push_str("                    allowed = false\n");
        code.push_str("                    break\n");
        code.push_str("                case .requireApproval:\n");
        code.push_str("                    requiredApprovals.append(rule.name)\n");
        code.push_str("                }\n");
        code.push_str("            }\n");
        code.push_str("        }\n\n");

        code.push_str("        return PolicyEvaluationResult(\n");
        code.push_str("            allowed: allowed,\n");
        code.push_str("            requiredApprovals: requiredApprovals,\n");
        code.push_str("            matchedRules: matchedRules\n");
        code.push_str("        )\n");
        code.push_str("    }\n\n");

        code.push_str("    private func evaluateRule(_ rule: TransferRule, transaction: Data, context: TransactionContext) -> Bool {\n");
        code.push_str("        switch rule.condition.conditionType {\n");
        code.push_str("        case .amountLimit:\n");
        code.push_str("            return evaluateAmountLimit(rule.condition, context: context)\n");
        code.push_str("        case .iterationWindow:\n");
        code.push_str(
            "            return evaluateIterationWindow(rule.condition, context: context)\n",
        );
        code.push_str("        case .whitelist:\n");
        code.push_str("            return evaluateWhitelist(rule.condition, context: context)\n");
        code.push_str("        case .blacklist:\n");
        code.push_str("            return evaluateBlacklist(rule.condition, context: context)\n");
        code.push_str("        case .signatureRequired:\n");
        code.push_str(
            "            return evaluateSignatureRequired(rule.condition, context: context)\n",
        );
        code.push_str("        case .custom:\n");
        code.push_str("            return evaluateCustomCondition(rule.condition, transaction: transaction, context: context)\n");
        code.push_str("        }\n");
        code.push_str("    }\n\n");

        code.push_str("    private func evaluateAmountLimit(_ condition: RuleCondition, context: TransactionContext) -> Bool {\n");
        code.push_str("        guard let maxStr = condition.parameters[\"maxAmount\"], let maxAmount = UInt64(maxStr) else { return false }\n");
        code.push_str("        return context.amount <= maxAmount\n");
        code.push_str("    }\n\n");

        code.push_str("    private func evaluateIterationWindow(_ condition: RuleCondition, context: TransactionContext) -> Bool {\n");
        code.push_str("        // Deterministic tick-based window check (no wall-clock).\n");
        code.push_str("        guard let maxStr = condition.parameters[\"maxIterations\"], let maxIterations = UInt64(maxStr) else { return false }\n");
        code.push_str("        return context.tick <= maxIterations\n");
        code.push_str("    }\n\n");

        code.push_str("    private func evaluateWhitelist(_ condition: RuleCondition, context: TransactionContext) -> Bool {\n");
        code.push_str("        guard let recipientList = condition.parameters[\"recipients\"] else { return false }\n");
        code.push_str("        let recipientStr = String(data: context.recipient, encoding: .utf8) ?? \"\"\n");
        code.push_str("        return recipientList.split(separator: \",\").map { $0.trimmingCharacters(in: .whitespaces) }.contains(recipientStr)\n");
        code.push_str("    }\n\n");

        code.push_str("    private func evaluateBlacklist(_ condition: RuleCondition, context: TransactionContext) -> Bool {\n");
        code.push_str("        guard let recipientList = condition.parameters[\"recipients\"] else { return true }\n");
        code.push_str("        let recipientStr = String(data: context.recipient, encoding: .utf8) ?? \"\"\n");
        code.push_str("        return !recipientList.split(separator: \",\").map { $0.trimmingCharacters(in: .whitespaces) }.contains(recipientStr)\n");
        code.push_str("    }\n\n");

        code.push_str("    private func evaluateSignatureRequired(_ condition: RuleCondition, context: TransactionContext) -> Bool {\n");
        code.push_str("        guard let countStr = condition.parameters[\"count\"], let requiredSignatures = Int(countStr) else { return false }\n");
        code.push_str("        return context.signatureCount >= requiredSignatures\n");
        code.push_str("    }\n\n");

        code.push_str("    private func evaluateCustomCondition(_ condition: RuleCondition, transaction: Data, context: TransactionContext) -> Bool {\n");
        code.push_str(
            "        // Custom condition evaluation - extend this method for specific policies\n",
        );
        code.push_str("        return (try? dsmSdk.evaluateCustomCondition(policyId: config.policyId, parameters: condition.parameters, transaction: transaction, context: context)) ?? false\n");
        code.push_str("    }\n\n");

        code.push_str("    func getPolicyRules() -> [TransferRule] {\n");
        code.push_str("        return config.rules\n");
        code.push_str("    }\n\n");

        code.push_str("    func getPolicyInfo() -> PolicyInfo {\n");
        code.push_str("        return PolicyInfo(\n");
        code.push_str("            name: config.name,\n");
        code.push_str("            version: config.version,\n");
        code.push_str("            ruleCount: config.rules.count,\n");
        code.push_str("            description: config.metadata[\"description\"]\n");
        code.push_str("        )\n");
        code.push_str("    }\n\n");

        code.push_str("}\n\n");

        // Transaction context
        code.push_str("struct TransactionContext {\n");
        code.push_str("    let sender: Data\n");
        code.push_str("    let recipient: Data\n");
        code.push_str("    let amount: UInt64\n");
        code.push_str("    let signatureCount: Int\n");
        code.push_str("    let tick: UInt64\n");
        code.push_str("    let metadata: [String: String]\n");
        code.push_str("}\n\n");

        // Policy info
        code.push_str("struct PolicyInfo {\n");
        code.push_str("    let name: String\n");
        code.push_str("    let version: String\n");
        code.push_str("    let ruleCount: Int\n");
        code.push_str("    let description: String?\n");
        code.push_str("}\n\n");

        Ok(code)
    }

    fn generate_factory_class(&self, spec: &VaultSpecification) -> Result<String> {
        let class_name = super::base_vault_name(spec);
        let mut code = String::new();

        code.push_str(&format!("class {}VaultFactory {{\n", class_name));
        code.push_str("    private let dsmSdk: DsmSdk\n\n");

        code.push_str("    init(dsmSdk: DsmSdk) {\n");
        code.push_str("        self.dsmSdk = dsmSdk\n");
        code.push_str("    }\n\n");

        code.push_str(&format!(
            "    func createClient(config: {}VaultConfig) -> {}VaultClient {{\n",
            class_name, class_name
        ));
        code.push_str(&format!(
            "        return {}VaultClient(dsmSdk: dsmSdk, config: config)\n",
            class_name
        ));
        code.push_str("    }\n\n");

        code.push_str("    // Callers must supply a valid vault_id from the DSM SDK\n");
        code.push_str("    // (sdk.generateVaultId() or from a prior DlvCreate operation).\n");
        code.push_str("}\n\n");

        Ok(code)
    }

    fn generate_test_vectors(&self) -> Result<String> {
        let mut code = String::new();

        code.push_str("// Test vectors for CI validation\n");
        code.push_str("struct TestVectors {\n");
        code.push_str("    // Minimal multi-sig condition\n");
        code.push_str("    static let multiSig = FulfillmentCondition.multiSignature(\n");
        code.push_str(
            "        MultiSignatureParams(publicKeys: [Data([1, 2, 3])], threshold: 1)\n",
        );
        code.push_str("    )\n");
        code.push_str("}\n\n");

        Ok(code)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::*;

    #[test]
    fn test_swift_vault_generation() {
        let vault_spec = VaultSpecification {
            name: "TestVault".to_string(),
            version: "1.0.0".to_string(),
            description: Some("A test vault for unit testing".to_string()),
            fulfillment_condition: crate::schema::FulfillmentConditionSpec::MultiSignature(
                crate::schema::MultiSignatureSpec {
                    public_keys: vec!["KEY1AAAAAA".to_string(), "KEY2AAAAAA".to_string()],
                    threshold: 2,
                },
            ),
            assets: vec![AssetDefinition {
                asset_id: "DSM".to_string(),
                amount: 1000,
                chain_state_hash: None,
                chain_state_number: None,
                metadata: None,
            }],
            tick_lock: None,
            recovery: None,
            metadata: None,
        };

        let spec = DsmSpecification::Vault(vault_spec);
        let generator = SwiftGenerator::new(false, false);

        match generator.generate(&spec) {
            Ok(generated_code) => {
                assert!(generated_code.contains("auto-generated by dsm-gen"));
                assert!(generated_code.contains("TestVaultClient"));
                assert!(generated_code.contains("class TestVaultClient"));
                assert!(generated_code.contains("func createVault"));
                assert!(generated_code.contains("func unlockVault"));
                assert!(generated_code.contains("indirect enum FulfillmentCondition"));
                assert!(generated_code.contains("bitcoinHtlc"));
                assert!(generated_code.contains("multiSignature"));
                assert!(generated_code.contains("randomWalkVerification"));
                assert!(generated_code.contains("VaultLifecycle"));
                // Invariant: no try!
                assert!(!generated_code.contains("try!"));
                // Invariant: no wall-clock
                assert!(!generated_code.contains("duration_seconds"));
            }
            Err(e) => panic!("generate failed: {}", e),
        }
    }
}
