//! TypeScript code generator for DSM specifications
//!
//! Generates type-safe TypeScript clients for DSM vaults and policies
//! with compile-time safety matching Algorand's experience.

use crate::generators::CodeGenerator;
use crate::schema::{DsmSpecification, PolicySpecification, VaultSpecification};
use anyhow::Result;

pub struct TypeScriptGenerator {
    include_factory: bool,
    include_test_vectors: bool,
}

impl TypeScriptGenerator {
    pub fn new(include_factory: bool, include_test_vectors: bool) -> Self {
        Self {
            include_factory,
            include_test_vectors,
        }
    }
}

impl CodeGenerator for TypeScriptGenerator {
    fn generate(&self, spec: &DsmSpecification) -> Result<String> {
        match spec {
            DsmSpecification::Vault(vault_spec) => self.generate_vault_client(vault_spec),
            DsmSpecification::Policy(policy_spec) => self.generate_policy_client(policy_spec),
        }
    }

    fn file_extension(&self) -> &'static str {
        "ts"
    }

    fn language_name(&self) -> &'static str {
        "TypeScript"
    }
}

impl TypeScriptGenerator {
    fn sanitize_identifier(name: &str) -> String {
        let sanitized: String = name.chars().filter(|c| c.is_alphanumeric()).collect();
        if sanitized.is_empty() {
            "Vault".to_string()
        } else {
            sanitized
        }
    }

    fn base_vault_name(spec: &VaultSpecification) -> String {
        let sanitized = Self::sanitize_identifier(&spec.name);
        let suffix = "vault";

        if sanitized.len() >= suffix.len() && sanitized.to_lowercase().ends_with(suffix) {
            sanitized[..sanitized.len() - suffix.len()].to_string()
        } else {
            sanitized
        }
    }

    fn base_policy_name(spec: &PolicySpecification) -> String {
        let sanitized = Self::sanitize_identifier(&spec.name);
        let suffix = "policy";

        if sanitized.len() >= suffix.len() && sanitized.to_lowercase().ends_with(suffix) {
            sanitized[..sanitized.len() - suffix.len()].to_string()
        } else {
            sanitized
        }
    }

    fn generate_vault_client(&self, spec: &VaultSpecification) -> Result<String> {
        let mut code = String::new();

        // Header comment
        code.push_str(&self.generate_header());

        // Imports
        code.push_str(&self.generate_imports());

        // Type definitions
        code.push_str(&self.generate_vault_types(spec)?);

        // Client class
        code.push_str(&self.generate_vault_client_class(spec)?);

        // Factory class (if requested)
        if self.include_factory {
            code.push_str(&self.generate_factory_class(spec)?);
        }

        // Test vectors (if requested)
        if self.include_test_vectors {
            code.push_str(&self.generate_test_vectors()?);
        }

        Ok(code)
    }

    fn generate_policy_client(&self, spec: &PolicySpecification) -> Result<String> {
        let mut code = String::new();

        // Header comment
        code.push_str(&self.generate_header());

        // Imports
        code.push_str(&self.generate_imports());

        // Type definitions
        code.push_str(&self.generate_policy_types(spec)?);

        // Client class
        code.push_str(&self.generate_policy_client_class(spec)?);

        // Factory class (if requested)
        if self.include_factory {
            code.push_str(&self.generate_factory_class_for_policy(spec)?);
        }

        Ok(code)
    }

    fn generate_header(&self) -> String {
        // Clockless/deterministic: never include wall-clock markers in generated output.
        let marker_suffix = String::new();

        format!(
            "// auto-generated by dsm-gen v{}{} — DO NOT EDIT\n\
             // This file was automatically generated from a DSM specification.\n\
             // For more information about DSM, visit: https://github.com/dsm-project\n\n",
            env!("CARGO_PKG_VERSION"),
            marker_suffix
        )
    }

    fn generate_imports(&self) -> String {
        r#"import { DsmSdk, DeviceId, Hash256, StateTransition } from '@dsm/sdk'

"#
        .to_string()
    }

    fn generate_vault_types(&self, spec: &VaultSpecification) -> Result<String> {
        let mut types = String::new();

        types.push_str(&format!(
            "// ---- Fulfillment condition types for {} ----\n\
             // Mirrors FulfillmentMechanism oneof in dsm_app.proto.\n\
             // Proto tag 1 (time_release) is absent — DSM is clockless.\n\n\
             export interface PaymentCondition {{\n\
               amount: bigint;\n\
               tokenId: string;\n\
               recipient: string;          // Base32 Crockford device_id\n\
               verificationState: Uint8Array; // BLAKE3-256 reference state hash\n\
             }}\n\n\
             export interface CryptoConditionParams {{\n\
               conditionHash: Uint8Array;  // BLAKE3(\"DSM/crypto-condition\\0\" || preimage)\n\
               publicParams: Uint8Array;\n\
             }}\n\n\
             export interface MultiSignatureParams {{\n\
               publicKeys: Uint8Array[];   // SPHINCS+ public keys\n\
               threshold: number;\n\
             }}\n\n\
             export interface StateReferenceParams {{\n\
               referenceStates: Uint8Array[]; // BLAKE3-256 hashes\n\
               parameters: Uint8Array;\n\
             }}\n\n\
             export interface RandomWalkParams {{\n\
               verificationKey: Uint8Array;\n\
               statement: string;\n\
             }}\n\n\
             export interface BitcoinHtlcParams {{\n\
               hashLock: Uint8Array;          // 32 bytes: SHA256(sk_V)\n\
               refundHashLock: Uint8Array;    // 32 bytes: SHA256(rk_V)\n\
               refundIterations: bigint;      // DSM chain-tick count (not wall time)\n\
               bitcoinPubkey: Uint8Array;     // 33 bytes: compressed pubkey\n\
               expectedBtcAmountSats: bigint;\n\
               network: 0 | 1 | 2;           // 0=mainnet 1=testnet 2=signet\n\
               minConfirmations: bigint;      // canonical=100 (dBTC §6.4)\n\
             }}\n\n\
             /** Recursive AND/OR wrappers */\n\
             export interface AndCondition {{ conditions: FulfillmentCondition[]; }}\n\
             export interface OrCondition  {{ conditions: FulfillmentCondition[]; }}\n\n\
             /** Discriminated union — field \"type\" selects the active variant. */\n\
             export type FulfillmentCondition =\n\
               | {{ type: 'payment';                  payment:                PaymentCondition }}\n\
               | {{ type: 'crypto_condition';         cryptoCondition:        CryptoConditionParams }}\n\
               | {{ type: 'multi_signature';          multiSignature:         MultiSignatureParams }}\n\
               | {{ type: 'state_reference';          stateReference:         StateReferenceParams }}\n\
               | {{ type: 'random_walk_verification'; randomWalkVerification: RandomWalkParams }}\n\
               | {{ type: 'bitcoin_htlc';             bitcoinHtlc:            BitcoinHtlcParams }}\n\
               | {{ type: 'and';                      and:                    AndCondition }}\n\
               | {{ type: 'or';                       or:                     OrCondition }};\n\n\
             // ---- Vault configuration ----\n\n\
             export interface AssetDefinition {{\n\
               assetId: string;\n\
               amount: bigint;\n\
               /** Base32 Crockford BLAKE3-256 for chain-anchored balance */\n\
               chainStateHash?: string;\n\
               chainStateNumber?: bigint;\n\
               metadata?: Record<string, string>;\n\
             }}\n\n\
             export interface CreateCfg {{\n\
               assets: AssetDefinition[];\n\
               fulfillmentCondition: FulfillmentCondition;\n\
               tickLock?: TickLockConfig;\n\
               recovery?: RecoveryConfig;\n\
             }}\n\n\
             export interface TickLockConfig {{\n\
               durationIterations: bigint;\n\
               action: 'return_to_owner' | {{ type: 'release_to_recipient'; recipient: string }} | 'burn';\n\
             }}\n\n\
             export interface RecoveryConfig {{\n\
               mechanism:\n\
                 | {{ type: 'multi_sig_recovery'; requiredSignatures: number; recoveryKeys: string[] }}\n\
                 | {{ type: 'social_recovery'; trustees: string[]; threshold: number }};\n\
             }}\n\n\
             export interface UnlockProof {{\n\
               // Provide the proof matching the vault's fulfillment condition.\n\
               conditionProof: Uint8Array;\n\
               signature: Uint8Array;\n\
             }}\n\n\
             export type VaultLifecycle = 'limbo' | 'active' | 'unlocked' | 'claimed' | 'invalidated';\n\n\
             export interface VaultStatus {{\n\
               id: Hash256;\n\
               lifecycle: VaultLifecycle;\n\
               assets: AssetDefinition[];\n\
               fulfillmentCondition: FulfillmentCondition;\n\
               createdAtState: bigint;\n\
               unlockedAtState?: bigint;\n\
             }}\n\n\
             export interface VaultMetadata {{\n\
               name: string;\n\
               version: string;\n\
               description?: string;\n\
               creator: DeviceId;\n\
               hash: Hash256;\n\
             }}\n\n",
            spec.name
        ));

        Ok(types)
    }

    fn generate_vault_client_class(&self, spec: &VaultSpecification) -> Result<String> {
        let base_name = Self::base_vault_name(spec);
        let class_name = format!("{base_name}VaultClient");

        Ok(format!(
            r#"/**
 * Client for {} Vault
 * {}
 */
export class {class_name} {{
  constructor(
    private readonly sdk: DsmSdk,
    private readonly vaultId?: Hash256
  ) {{}}

  /* ------------ Creation ------------ */
  
  /**
   * Create a new {} vault
   */
  static async create(sdk: DsmSdk, cfg: CreateCfg): Promise<{class_name}> {{
    if (!cfg.assets || cfg.assets.length === 0) {{
      throw new Error('At least one asset must be specified');
    }}
    if (!cfg.fulfillmentCondition) {{
      throw new Error('fulfillmentCondition must be specified');
    }}
    
    // Create vault through DSM SDK
    const vaultId = await sdk.vault.create({{
      assets: cfg.assets,
      fulfillmentCondition: cfg.fulfillmentCondition,
      tickLock: cfg.tickLock,
      recovery: cfg.recovery,
    }});
    
    return new {class_name}(sdk, vaultId);
  }}

  /* ------------ Getters ------------ */
  
  /**
   * Get current vault status
   */
  async status(): Promise<VaultStatus> {{
    if (!this.vaultId) {{
      throw new Error('Vault not initialized');
    }}
    
    return await this.sdk.vault.status(this.vaultId);
  }}

  /**
   * Get vault metadata
   */
  async metadata(): Promise<VaultMetadata> {{
    if (!this.vaultId) {{
      throw new Error('Vault not initialized');
    }}
    
    return await this.sdk.vault.metadata(this.vaultId);
  }}

  /**
   * Get vault ID
   */
  getId(): Hash256 | undefined {{
    return this.vaultId;
  }}

  /* ------------ Actions ------------ */
  
  /**
   * Unlock the vault with a fulfillment proof.
   * The proof must satisfy the vault's FulfillmentCondition.
   */
  async unlock(proof: UnlockProof): Promise<StateTransition> {{
    if (!this.vaultId) {{
      throw new Error('Vault not initialized — call create() first');
    }}
    await this.validateUnlockProof(proof);
    return await this.sdk.vault.unlock(this.vaultId, proof);
  }}

  /**
   * Check if a proof satisfies the vault's fulfillment condition.
   */
  async canUnlock(proof: UnlockProof): Promise<boolean> {{
    try {{
      await this.validateUnlockProof(proof);
      return true;
    }} catch {{
      return false;
    }}
  }}

  /* ------------ Private Methods ------------ */
  
  private static validateCreateConfig(_cfg: CreateCfg): void {{
    // validation is inline in create()
  }}
  
  private async validateUnlockProof(proof: UnlockProof): Promise<void> {{
    const status = await this.status();

    if (status.lifecycle === 'unlocked' || status.lifecycle === 'claimed') {{
      throw new Error(`Vault is already ${{status.lifecycle}}`);
    }}
    if (status.lifecycle === 'invalidated') {{
      throw new Error('Vault has been invalidated');
    }}

    // Condition-specific validation — delegates final proof verification to SDK.
    const cond = status.fulfillmentCondition;
    switch (cond.type) {{
      case 'payment':
      case 'crypto_condition':
      case 'state_reference':
      case 'random_walk_verification':
      case 'bitcoin_htlc':
        if (!proof.conditionProof || proof.conditionProof.length === 0) {{
          throw new Error(`conditionProof required for ${{cond.type}} unlock`);
        }}
        break;
      case 'multi_signature':
        if (!proof.conditionProof || proof.conditionProof.length === 0) {{
          throw new Error('conditionProof (serialised multi-sig bundle) required');
        }}
        break;
      case 'and':
      case 'or':
        // Composite conditions — proof bundle validated by the SDK
        if (!proof.conditionProof || proof.conditionProof.length === 0) {{
          throw new Error(`conditionProof required for composite (${{cond.type}}) unlock`);
        }}
        break;
    }}
  }}
}}

"#,
            spec.name,
            spec.description
                .as_deref()
                .unwrap_or("DSM Deterministic Limbo Vault"),
            spec.name,
            class_name = class_name,
        ))
    }

    fn generate_factory_class(&self, spec: &VaultSpecification) -> Result<String> {
        let base_name = Self::base_vault_name(spec);
        let class_name = format!("{base_name}VaultFactory");
        let vault_class_name = format!("{base_name}VaultClient");

        Ok(format!(
            r#"/**
 * Factory for managing multiple {} vaults
 */
export class {class_name} {{
  private vaults = new Map<Hash256, {vault_class_name}>();

  constructor(private readonly sdk: DsmSdk) {{}}

  /**
   * Create a new vault and add it to the factory
   */
  async createVault(cfg: CreateCfg): Promise<{vault_class_name}> {{
    const vault = await {vault_class_name}.create(this.sdk, cfg);
    const vaultId = vault.getId();
    
    if (vaultId) {{
      this.vaults.set(vaultId, vault);
    }}
    
    return vault;
  }}

  /**
   * Get an existing vault by ID
   */
  getVault(vaultId: Hash256): {vault_class_name} | undefined {{
    return this.vaults.get(vaultId);
  }}

  /**
   * List all managed vaults
   */
  listVaults(): {vault_class_name}[] {{
    return Array.from(this.vaults.values());
  }}

  /**
   * Remove a vault from management
   */
  removeVault(vaultId: Hash256): boolean {{
    return this.vaults.delete(vaultId);
  }}

  /**
   * Get vault count
   */
  getVaultCount(): number {{
    return this.vaults.size;
  }}
}}

"#,
            spec.name,
            class_name = class_name,
            vault_class_name = vault_class_name,
        ))
    }

    fn generate_policy_types(&self, spec: &PolicySpecification) -> Result<String> {
        Ok(format!(
            "// Policy types for {}\n\n\
             export interface TransferParams {{\n\
               from: DeviceId;\n\
               to: DeviceId;\n\
               amount: bigint;\n\
               assetId: string;\n\
               metadata?: Record<string, string>;\n\
             }}\n\n\
             export interface ValidationResult {{\n\
               isValid: boolean;\n\
               errors: string[];\n\
               requiredProofs: string[];\n\
             }}\n\n\
             export interface ProofData {{\n\
               type: 'merkle_proof' | 'zk_proof' | 'signature' | 'hash_chain_proof';\n\
               data: Uint8Array;\n\
             }}\n\n\
             export interface PolicyConfig {{\n\
               name: string;\n\
               version: string;\n\
               description?: string;\n\
             }}\n\n",
            spec.name
        ))
    }

    fn generate_policy_client_class(&self, spec: &PolicySpecification) -> Result<String> {
        let class_name = format!(
            "{}PolicyClient",
            spec.name
                .chars()
                .filter(|c| c.is_alphanumeric())
                .collect::<String>()
        );

        Ok(format!(
            r#"/**
 * Client for {} Policy
 * {}
 */
export class {class_name} {{
  constructor(private readonly sdk: DsmSdk) {{}}

  /**
   * Simulate a transfer to check if it would be allowed
   */
  async simulateTransfer(params: TransferParams): Promise<ValidationResult> {{
    // Implementation would validate against policy rules
    return await this.sdk.policy.simulate(params);
  }}

  /**
   * Validate a proof against policy requirements
   */
  async validateProof(proof: ProofData): Promise<boolean> {{
    return await this.sdk.policy.validateProof(proof);
  }}

  /**
   * Execute a transfer following policy rules
   */
  async executeTransfer(params: TransferParams, proofs: ProofData[]): Promise<StateTransition> {{
    // Validate transfer against policy
    const validation = await this.simulateTransfer(params);
    if (!validation.isValid) {{
      throw new Error(`Transfer validation failed: ${{validation.errors.join(', ')}}`);
    }}

    // Validate required proofs
    for (const proof of proofs) {{
      const isValidProof = await this.validateProof(proof);
      if (!isValidProof) {{
        throw new Error(`Invalid proof of type: ${{proof.type}}`);
      }}
    }}

    return await this.sdk.policy.executeTransfer(params, proofs);
  }}
}}

"#,
            spec.name,
            spec.description
                .as_deref()
                .unwrap_or("DSM Content-Addressed Token Policy"),
            class_name = class_name
        ))
    }

    fn generate_factory_class_for_policy(&self, spec: &PolicySpecification) -> Result<String> {
        let base_name = Self::base_policy_name(spec);
        let class_name = format!("{base_name}PolicyFactory");
        let policy_class_name = format!("{base_name}PolicyClient");

        Ok(format!(
            r#"/**
 * Factory for managing {base_name} policy instances
 * Policies are typically singletons, but this factory allows for multiple configurations
 */
export class {class_name} {{
  private policies = new Map<string, {policy_class_name}>();

  constructor(private readonly sdk: DsmSdk) {{}}

  /**
   * Create a new policy instance
   */
  async createPolicy(cfg: PolicyConfig): Promise<{policy_class_name}> {{
    const policy = await {policy_class_name}.create(this.sdk, cfg);
    const policyId = policy.getId();

    if (policyId) {{
      this.policies.set(policyId, policy);
    }}

    return policy;
  }}

  /**
   * Get an existing policy by ID
   */
  getPolicy(policyId: string): {policy_class_name} | undefined {{
    return this.policies.get(policyId);
  }}

  /**
   * List all managed policies
   */
  listPolicies(): {policy_class_name}[] {{
    return Array.from(this.policies.values());
  }}

  /**
   * Remove a policy from management
   */
  removePolicy(policyId: string): boolean {{
    return this.policies.delete(policyId);
  }}

  /**
   * Get policy count
   */
  getPolicyCount(): number {{
    return this.policies.size;
  }}
}}

"#
        ))
    }

    fn generate_test_vectors(&self) -> Result<String> {
        Ok(r#"
/* ------------ Test Vectors ------------ */

/**
 * Golden test vectors for CI validation
 * These vectors are embedded at compile time to ensure correctness
 */
export const TEST_VECTORS = {
  // Test vectors would be generated based on the specification
  // and embedded here for CI validation
} as const;

"#
        .to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::*;

    #[test]
    fn test_typescript_vault_generation() {
        let vault_spec = VaultSpecification {
            name: "TestVault".to_string(),
            version: "1.0.0".to_string(),
            description: Some("A test vault for unit testing".to_string()),
            fulfillment_condition: crate::schema::FulfillmentConditionSpec::MultiSignature(
                crate::schema::MultiSignatureSpec {
                    public_keys: vec!["KEY1AAAAAA".to_string(), "KEY2AAAAAA".to_string()],
                    threshold: 2,
                },
            ),
            assets: vec![AssetDefinition {
                asset_id: "DSM".to_string(),
                amount: 1000,
                chain_state_hash: None,
                chain_state_number: None,
                metadata: None,
            }],
            tick_lock: None,
            recovery: None,
            metadata: None,
        };

        let spec = DsmSpecification::Vault(vault_spec);
        let generator = TypeScriptGenerator::new(false, false);

        match generator.generate(&spec) {
            Ok(generated_code) => {
                assert!(generated_code.contains("auto-generated by dsm-gen"));
                assert!(generated_code.contains("TestVaultClient"));
                assert!(generated_code.contains("export class TestVaultClient"));
                assert!(generated_code.contains("static async create"));
                assert!(generated_code.contains("async unlock"));
                // Invariant checks: must not emit wall-clock or banned terms
                assert!(!generated_code.contains("duration_seconds"));
                assert!(!generated_code.contains("time_lock"));
                assert!(!generated_code.contains("TimeLock"));
                assert!(!generated_code.contains("JSON.stringify"));
                assert!(!generated_code.contains("JSON.parse"));
                // Must contain FulfillmentCondition union
                assert!(generated_code.contains("FulfillmentCondition"));
                assert!(generated_code.contains("bitcoin_htlc"));
                assert!(generated_code.contains("multi_signature"));
                assert!(generated_code.contains("random_walk_verification"));
            }
            Err(e) => panic!("generate failed: {}", e),
        }
    }
}
