/* Automatically generated by cbindgen for DSM SDK */
#include <jni.h>

/* Generated with cbindgen:0.28.0 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

uint8_t *dsm_process_envelope_protobuf(const uint8_t *envelope_bytes,
                                       uintptr_t envelope_len,
                                       uintptr_t *out_len);

void dsm_free_envelope_bytes(uint8_t *bytes, uintptr_t len);
