/* Automatically generated by cbindgen for DSM SDK */

/* Generated with cbindgen:0.28.0 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

uint8_t *dsm_process_envelope_protobuf(const uint8_t *envelope_bytes,
                                       uintptr_t envelope_len,
                                       uintptr_t *out_len);

uint8_t *dsm_dispatch_startup_request(const uint8_t *request_bytes,
                                      uintptr_t request_len,
                                      uintptr_t *out_len);

uint8_t *dsm_dispatch_ingress_request(const uint8_t *request_bytes,
                                      uintptr_t request_len,
                                      uintptr_t *out_len);

void dsm_free_envelope_bytes(uint8_t *bytes, uintptr_t len);

bool dsm_set_storage_base_dir(const char *path_utf8);

bool dsm_configure_env(const char *config_path_utf8);

bool dsm_initialize_sdk(void);

bool dsm_init_dsm_sdk(const char *config_path_utf8);

bool dsm_initialize_sdk_context(const uint8_t *device_id,
                                uintptr_t device_id_len,
                                const uint8_t *genesis_hash,
                                uintptr_t genesis_hash_len,
                                const uint8_t *binding_key,
                                uintptr_t binding_key_len);
